import React from "react";
import ReactExport from 'react-export-excel';
import { CBCTypeId, VBCTypeId, ZBCADDMORE, ZBCTypeId, ZBCTypeIdFull } from "../../config/constants";
import {
    Fuel, FuelTempData,
    RMDomesticZBC, RMDomesticZBCTempData, RMDomesticVBC, RMDomesticVBCTempData,
    RMImportZBC, RMImportZBCTempData, RMImportVBC, RMImportVBCTempData,
    RMSpecification, RMSpecificationXLTempData,
    Vendor, VendorTempData,
    Labour, LabourTempData,
    Overhead, OverheadTempData, Profit, ProfitTempData,
    ZBCOperation, ZBCOperationTempData, VBCOperation, VBCOperationTempData,
    MachineZBC, MachineZBCTempData, MachineVBC, MachineVBCTempData, MHRMoreZBC, MHRMoreZBCTempData,
    PartComponent, PartComponentTempData, ProductComponent, ProductComponentTempData, BOMUploadTempData, BOMUpload,
    BOP_ZBC_DOMESTIC, BOP_ZBC_DOMESTIC_TempData, BOP_VBC_DOMESTIC, BOP_VBC_DOMESTIC_TempData,
    BOP_ZBC_IMPORT, BOP_ZBC_IMPORT_TempData, BOP_VBC_IMPORT, BOP_VBC_IMPORT_TempData,
    VOLUME_ACTUAL_ZBC, VOLUME_ACTUAL_ZBC_TEMPDATA, VOLUME_ACTUAL_VBC, VOLUME_ACTUAL_VBC_TEMPDATA,
    VOLUME_BUDGETED_ZBC, VOLUME_BUDGETED_ZBC_TEMPDATA, VOLUME_BUDGETED_VBC, VOLUME_BUDGETED_VBC_TEMPDATA,
    ZBCInterestRate, ZBCInterestRateTempData, VBCInterestRate, VBCInterestRateTempData, RMDomesticCBC, RMDomesticCBCTempData, RMImportCBC, RMImportCBCTempData, MachineCBC, MachineCBCTempData, BOP_CBC_DOMESTIC, BOP_CBC_IMPORT, BOP_CBC_IMPORT_TempData, BOP_CBC_DOMESTIC_TempData, VOLUME_BUDGETED_CBC_TEMPDATA, VOLUME_ACTUAL_CBC_TEMPDATA, CBCOperationTempData, VOLUME_ACTUAL_CBC, VOLUME_BUDGETED_CBC, CBCOperation, CBCInterestRateTempData, CBCInterestRate
} from '../../config/masterData';
import { checkVendorPlantConfigurable, getConfigurationKey } from "../../helper";

const ExcelFile = ReactExport.ExcelFile;
const ExcelSheet = ReactExport.ExcelFile.ExcelSheet;
const ExcelColumn = ReactExport.ExcelFile.ExcelColumn;

export const checkRM_Process_OperationConfigurable = (excelData) => {
    return excelData.filter((el) => {
        if (getConfigurationKey().IsAutoGeneratedRawMaterialCode === true) {
            if (el.value === 'RawMaterialCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedProcessCode === true) {
            if (el.value === 'ProcessCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedOperationCode === true) {
            if (el.value === 'OperationCode') return false;
        }
        return true;
    })
}

export const checkLabourRateConfigure = (excelData) => {
    return excelData.filter((el) => {
        if (getConfigurationKey().IsOperationLabourRateConfigure === false) {
            if (el.value === 'LabourRate') return false;
        }
        if (getConfigurationKey().IsDestinationPlantConfigure === false) {
            if (el.value === 'DestinationPlant') return false;
            if (el.value === 'DestinationPlantCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedOperationCode === true) {
            if (el.value === 'OperationCode') return false;
        }
        return true;
    })
}
/**
* @method checkVendorPlantConfig
* @description CONDITION TO CHECK:- TO AVOID VENDOR PLANT IF NOT CONFIGURABLE FROM INITIALIZER
*/
export const checkVendorPlantConfig = (excelData, type = '') => {
    return excelData.filter((el) => {
        if (checkVendorPlantConfigurable() === false) {
            if (el.value === 'VendorPlant') return false;
            /**********************DON'T REMOVE NOW MAY BE USED LATER**********************************/
            // if (el.value === 'LabourRate') return false;
            // if (el.value === 'VendorName') return false;
            // if (el.value === 'VendorPlantCode') return false;
            // if (el.value === 'DestinationPlant') return false;
            // if (el.value === 'DestinationPlantCode') return false;

        }
        if (getConfigurationKey().IsDestinationPlantConfigure === false) {
            if (el.value === 'DestinationPlant') return false;
            if (el.value === 'DestinationPlantCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedRawMaterialCode === true) {
            if (el.value === 'RawMaterialCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedProcessCode === true) {
            if (el.value === 'ProcessCode') return false;
        }
        if (type === CBCTypeId && getConfigurationKey().IsCBCApplicableOnPlant === false) {
            if (el.value === 'DestinationPlantName') return false;
            if (el.value === 'DestinationPlantCode') return false;
        }
        return true;
    })
}
class Downloadxls extends React.Component {
    /**
    * @method renderSwitch
    * @description Switch case for different xls file head according to master
    */
    renderSwitch = (master) => {
        switch (master) {
            case 'RMSpecification':
                return this.returnExcelColumn(RMSpecification, RMSpecificationXLTempData);
            case 'Vendor':
                return this.returnExcelColumn(Vendor, VendorTempData);
            case 'Overhead':
                return this.returnExcelColumn(Overhead, OverheadTempData);
            case 'Fuel':
                return this.returnExcelColumn(Fuel, FuelTempData);
            case 'Profit':
                return this.returnExcelColumn(Profit, ProfitTempData);
            case 'Labour':
                return this.returnExcelColumn(Labour, LabourTempData);
            case 'PartComponent':
                return this.returnExcelColumn(PartComponent, PartComponentTempData);
            case 'ProductComponent':
                return this.returnExcelColumn(ProductComponent, ProductComponentTempData);
            case 'BOM':
                return this.returnExcelColumn(BOMUpload, BOMUploadTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method renderZBCSwitch
    * @description Switch case for different xls file head according to master
    */
    renderZBCSwitch = (master) => {
        switch (master) {
            case 'RMDomestic':
                return this.returnExcelColumn(checkRM_Process_OperationConfigurable(RMDomesticZBC), RMDomesticZBCTempData);
            case 'RMImport':
                return this.returnExcelColumn(checkRM_Process_OperationConfigurable(RMImportZBC), RMImportZBCTempData);
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(ZBCOperation), ZBCOperationTempData);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(MachineZBC), MachineZBCTempData);
            case ZBCADDMORE:
                return this.returnExcelColumn(checkRM_Process_OperationConfigurable(MHRMoreZBC), MHRMoreZBCTempData);
            case 'BOPDomestic':
            case 'InsertDomestic':
                return this.returnExcelColumn(BOP_ZBC_DOMESTIC, BOP_ZBC_DOMESTIC_TempData);
            case 'BOPImport':
            case 'InsertImport':
                return this.returnExcelColumn(BOP_ZBC_IMPORT, BOP_ZBC_IMPORT_TempData);
            case 'ActualVolume':
                return this.returnExcelColumn(VOLUME_ACTUAL_ZBC, VOLUME_ACTUAL_ZBC_TEMPDATA);
            case 'BudgetedVolume':
                return this.returnExcelColumn(VOLUME_BUDGETED_ZBC, VOLUME_BUDGETED_ZBC_TEMPDATA);
            case 'InterestRate':
                return this.returnExcelColumn(ZBCInterestRate, ZBCInterestRateTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method renderVBCSwitch
    * @description Switch case for different xls file head according to master
    */
    renderVBCSwitch = (master) => {
        switch (master) {
            case 'RMDomestic':
                return this.returnExcelColumn(checkVendorPlantConfig(RMDomesticVBC), RMDomesticVBCTempData);
            case 'RMImport':
                return this.returnExcelColumn(checkVendorPlantConfig(RMImportVBC), RMImportVBCTempData);
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(VBCOperation), VBCOperationTempData);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(MachineVBC), MachineVBCTempData);
            case 'InsertDomestic':
            case 'BOPDomestic':
                return this.returnExcelColumn(checkVendorPlantConfig(BOP_VBC_DOMESTIC), BOP_VBC_DOMESTIC_TempData);
            case 'BOPImport':
            case 'InsertImport':
                return this.returnExcelColumn(checkVendorPlantConfig(BOP_VBC_IMPORT), BOP_VBC_IMPORT_TempData);
            case 'ActualVolume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_ACTUAL_VBC), VOLUME_ACTUAL_VBC_TEMPDATA);
            case 'BudgetedVolume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_BUDGETED_VBC), VOLUME_BUDGETED_VBC_TEMPDATA);
            case 'InterestRate':
                return this.returnExcelColumn(VBCInterestRate, VBCInterestRateTempData);
            default:
                return 'foo';
        }
    }
    /**
     * @method renderVBCSwitch
     * @description Switch case for different xls file head according to master
     */
    renderCBCSwitch = (master) => {
        switch (master) {
            case 'RMDomestic':
                return this.returnExcelColumn(checkVendorPlantConfig(RMDomesticCBC, CBCTypeId), RMDomesticCBCTempData);
            case 'RMImport':
                return this.returnExcelColumn(checkVendorPlantConfig(RMImportCBC, CBCTypeId), RMImportCBCTempData);
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(CBCOperation, CBCTypeId), CBCOperationTempData);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(MachineCBC, CBCTypeId), MachineCBCTempData);
            case 'BOPDomestic':
                return this.returnExcelColumn(checkVendorPlantConfig(BOP_CBC_DOMESTIC, CBCTypeId), BOP_CBC_DOMESTIC_TempData);
            case 'BOPImport':
                return this.returnExcelColumn(checkVendorPlantConfig(BOP_CBC_IMPORT, CBCTypeId), BOP_CBC_IMPORT_TempData);
            case 'ActualVolume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_ACTUAL_CBC, CBCTypeId), VOLUME_ACTUAL_CBC_TEMPDATA);
            case 'BudgetedVolume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_BUDGETED_CBC, CBCTypeId), VOLUME_BUDGETED_CBC_TEMPDATA);
            case 'InterestRate':
                return this.returnExcelColumn(CBCInterestRate, CBCInterestRateTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method returnExcelColumn
    * @description Used to get excel column names
    */
    returnExcelColumn = (data = [], TempData) => {
        const { fileName, failedData, isFailedFlag } = this.props;

        if (isFailedFlag) {

            //BELOW CONDITION TO ADD 'REASON' COLUMN WHILE DOWNLOAD EXCEL SHEET IN CASE OF FAILED
            let isContentReason = data.filter(d => d.label === 'Reason')
            if (isContentReason.length === 0) {
                let addObj = { label: 'Reason', value: 'Reason' }
                data.push(addObj)
            }
        }

        return (<ExcelSheet data={isFailedFlag ? failedData : TempData} name={fileName}>
            {data && data.map((ele, index) => <ExcelColumn key={index} label={ele.label} value={ele.value} style={ele.style} />)}
        </ExcelSheet>);
    }

    render() {
        const { isFailedFlag, fileName, isZBCVBCTemplate, isMachineMoreTemplate, costingTypeId } = this.props;
        // DOWNLOAD FILE:- CALLED WHEN ZBC FILE FAILED   hideElement={true}
        // ZBC_MACHINE_MORE THIS IS ADDITIONAL CONDITION ONLY FOR MACHINE MORE DETAIL FROM MACHINE MASTER
        if (isFailedFlag && (costingTypeId === ZBCTypeId || costingTypeId === ZBCADDMORE) && (fileName === 'RMDomestic' || fileName === 'RMImport' || fileName === 'Operation' || fileName === 'Machine' || fileName === 'BOPDomestic' || fileName === 'InsertDomestic' || fileName === 'InsertImport' || fileName === 'BOPImport' || fileName === 'ActualVolume' || fileName === 'BudgetedVolume' || fileName === 'InterestRate')) {

            return (
                <ExcelFile hideElement={true} filename={`${fileName}ZBC`} fileExtension={'.xls'} >
                    {isMachineMoreTemplate ? this.renderZBCSwitch(costingTypeId) : this.renderZBCSwitch(fileName)}
                </ExcelFile>
            );
        }

        // DOWNLOAD FILE:- CALLED WHEN VBC FILE FAILED
        if (isFailedFlag && costingTypeId === VBCTypeId && (fileName === 'RMDomestic' || fileName === 'RMImport' || fileName === 'Operation' || fileName === 'Machine' || fileName === 'BOPDomestic' || fileName === 'InsertDomestic' || fileName === 'InsertImport' || fileName === 'BOPImport' || fileName === 'ActualVolume' || fileName === 'BudgetedVolume' || fileName === 'InterestRate')) {
            return (
                <ExcelFile hideElement={true} filename={`${fileName}VBC`} fileExtension={'.xls'} >
                    {this.renderVBCSwitch(fileName)}
                </ExcelFile>
            );
        }
        // DOWNLOAD FILE:- CALLED WHEN CBC FILE FAILED
        if (isFailedFlag && costingTypeId === CBCTypeId && (fileName === 'RMDomestic' || fileName === 'RMImport' || fileName === 'Operation' || fileName === 'Machine' || fileName === 'BOPDomestic' || fileName === 'BOPImport' || fileName === 'ActualVolume' || fileName === 'BudgetedVolume' || fileName === 'InterestRate')) {
            return (
                <ExcelFile hideElement={true} filename={`${fileName}CBC`} fileExtension={'.xls'} >
                    {this.renderCBCSwitch(fileName)}
                </ExcelFile>
            );
        }
        // DOWNLOAD FILE:- CALLED WHEN FILE FAILED APART FROM ZBC AND VBC
        if (isFailedFlag && (fileName === 'RMSpecification' || fileName === 'Vendor' || fileName === 'Overhead' || fileName === 'Fuel' || fileName === 'Labour' || fileName === 'PartComponent' || fileName === 'ProductComponent')) {
            return (
                <ExcelFile hideElement={true} filename={fileName} fileExtension={'.xls'} >
                    {this.renderSwitch(fileName)}
                </ExcelFile>
            );
        }

        // DISPLAY RADIO BUTTON ZBC AND VBC, WITH FILE DOWNLOAD BUTTON
        if (isZBCVBCTemplate) {
            return (
                <>
                    {costingTypeId === ZBCTypeId &&
                        <ExcelFile filename={`${fileName}ZBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download ZBC</button>}>
                            {fileName ? this.renderZBCSwitch(fileName) : ''}
                        </ExcelFile>}

                    {costingTypeId === VBCTypeId &&
                        <ExcelFile filename={`${fileName}VBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download VBC</button>}>
                            {fileName ? this.renderVBCSwitch(fileName) : ''}
                        </ExcelFile>}
                    {costingTypeId === CBCTypeId &&
                        <ExcelFile filename={`${fileName}CBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download CBC</button>}>
                            {fileName ? this.renderCBCSwitch(fileName) : ''}
                        </ExcelFile>}
                    {/* ZBC_MACHINE_MORE THIS IS ADDITIONAL CONDITION ONLY FOR MACHINE MORE DETAIL FROM MACHINE MASTER */}
                    {costingTypeId === ZBCADDMORE &&
                        <ExcelFile filename={`MACHINE_MORE_ZBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download ZBC DETAIL</button>}>
                            {fileName ? this.renderZBCSwitch(costingTypeId) : ''}

                        </ExcelFile>}
                </>
            );
        }

        // DISPLAY DOWNLOAD FILE BUTTON EXCEPT ZBC AND VBC TEMPLATES
        return (
            <ExcelFile filename={fileName} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download File</button>}>
                {fileName ? this.renderSwitch(fileName) : ''}
            </ExcelFile>
        );
    }
}

export default Downloadxls;