import React from "react";
import ReactExport from 'react-export-excel';
import { ASSEMBLYORCOMPONENTSRFQ, BOUGHTOUTPARTSRFQ, CBCADDMORE, CBCADDMOREOPERATION, CBCTypeId, RAWMATERIALSRFQ, VBCADDMORE, VBCADDMOREOPERATION, VBCTypeId, ZBCADDMORE, ZBCADDMOREOPERATION, ZBCTypeId } from "../../config/constants";
import {
    Fuel, FuelTempData,
    RMDomesticZBC, RMDomesticZBCTempData, RMDomesticVBC, RMDomesticVBCTempData,
    RMImportZBC, RMImportZBCTempData, RMImportVBC, RMImportVBCTempData,
    RMSpecification, RMSpecificationXLTempData,
    Vendor, VendorTempData,
    Labour, LabourTempData,
    Overhead, OverheadTempData, OverheadVBC, OverheadVBC_TempData, OverheadCBC, OverheadCBC_TempData, Profit, ProfitTempData, ProfitVBC, ProfitTempDataVBC, ProfitCBC, ProfitTempDataCBC,
    ZBCOperation, ZBCOperationTempData, VBCOperation, VBCOperationTempData,
    MachineZBC, MachineZBCTempData, MachineVBC, MachineVBCTempData, MHRMoreZBC, MHRMoreZBCTempData,
    PartComponent, PartComponentTempData, ProductComponent, ProductComponentTempData, BOMUploadTempData, BOMUpload,
    BOP_ZBC_DOMESTIC, BOP_ZBC_DOMESTIC_TempData, BOP_VBC_DOMESTIC, BOP_VBC_DOMESTIC_TempData,
    BOP_ZBC_IMPORT, BOP_ZBC_IMPORT_TempData, BOP_VBC_IMPORT, BOP_VBC_IMPORT_TempData,
    VOLUME_ACTUAL_ZBC, VOLUME_ACTUAL_ZBC_TEMPDATA, VOLUME_ACTUAL_VBC, VOLUME_ACTUAL_VBC_TEMPDATA,
    VOLUME_BUDGETED_ZBC, VOLUME_BUDGETED_ZBC_TEMPDATA, VOLUME_BUDGETED_VBC, VOLUME_BUDGETED_VBC_TEMPDATA,
    ZBCInterestRate, ZBCInterestRateTempData, VBCInterestRate, VBCInterestRateTempData, RMDomesticCBC, RMDomesticCBCTempData, RMImportCBC, RMImportCBCTempData, MachineCBC, MachineCBCTempData, BOP_CBC_DOMESTIC, BOP_CBC_IMPORT, BOP_CBC_IMPORT_TempData, BOP_CBC_DOMESTIC_TempData, VOLUME_BUDGETED_CBC_TEMPDATA, VOLUME_ACTUAL_CBC_TEMPDATA, CBCOperationTempData, VOLUME_ACTUAL_CBC, VOLUME_BUDGETED_CBC, CBCOperation, CBCInterestRateTempData, CBCInterestRate, AddRFQUpload, AddRFQTempData, BUDGET_ZBC, BUDGET_ZBC_TEMPDATA, BUDGET_VBC_TEMPDATA, BUDGET_VBC, BUDGET_CBC_TEMPDATA, BUDGET_CBC, ZBCOperationSmallForm, VBCOperationSmallForm, CBCOperationSmallForm, DETAILED_BOP, BOP_DETAILED_DOMESTIC, BOP_DETAILED_DOMESTIC_TempData, BOP_DETAILED_IMPORT, BOP_DETAILED_IMPORT_TempData,
    IndexCommodityListing, IndexCommodityListingTempData, CommodityInIndexListing, CommodityInIndexListingTempData,
    StandardizedCommodityNameTempData, StandardizedCommodityNameListing,
    CommodityStandardTempData,
    IndexDataListingTempData,
    IndexDataListing,
    CommodityStandard,
    AddBoughtOutPartsHeaderData,
    AddRawMaterialHeaderData,
    AddAssemblyOrComponentHeaderData,
    AddBoughtOutPartsTempData,
    AddRawMaterialTempData,
    AddAssemblyOrComponentTempData
} from '../../config/masterData';
import { checkVendorPlantConfigurable, getConfigurationKey, showBopLabel, updateBOPValues } from "../../helper";
import { checkSAPCodeinExcel } from "./DownloadUploadBOMxls";
import { IsShowFreightAndShearingCostFields } from "../../helper";
import { withLocalization, useWithLocalization } from "../../helper/core";
import { withTranslation } from "react-i18next";

const ExcelFile = ReactExport.ExcelFile;
const ExcelSheet = ReactExport.ExcelFile.ExcelSheet;
const ExcelColumn = ReactExport.ExcelFile.ExcelColumn;
const bopMasterName = showBopLabel();

export const checkRM_Process_OperationConfigurable = (excelData) => {

    return excelData.filter((el) => {
        if (getConfigurationKey().IsAutoGeneratedRawMaterialCode && el.value === 'RawMaterialCode') return false;
        if (getConfigurationKey().IsAutoGeneratedProcessCode && el.value === 'ProcessCode') return false;
        if (getConfigurationKey().IsAutoGeneratedOperationCode && el.value === 'OperationCode') return false;
        if (getConfigurationKey().IsAutoGeneratedMachineNumber && el.value === 'MachineNo') return false;
        if (IsShowFreightAndShearingCostFields() === false) {
            const freightAndShearingCostKeys = ['FreightCost', 'ShearingCost', 'RMFreightCost', 'RMShearingCost', 'RawMaterialFreightCostConversion', 'RawMaterialShearingCostConversion '];
            if (freightAndShearingCostKeys.includes(el.value)) return false;
        }

        if (getConfigurationKey().IsShowCRMHead === false) {
            const crmHeadKeys = ['LoanCRMHead', 'InterestCRMHead', 'WorkingShiftCRMHead', 'DepreciationCRMHead', 'AnnualMaintanceCRMHead', 'AnnualConsumableCRMHead', 'AnnualInsuranceCRMHead', 'BuildingCRMHead', 'MachineFloorCRMHead', 'OtherYearlyCRMHead', 'FuelCRMHead', 'PowerCRMHead', 'LabourCRMHead']

            for (const index in crmHeadKeys) {
                if (el.value === crmHeadKeys[index]) {
                    return false; // Exclude the element if el.value matches any entry in the array
                }
            }
        }
        return true; // Include the element if none of the conditions above are met
    });
}

export const checkLabourRateConfigure = (excelData) => {
    return excelData.filter((el) => {
        if (getConfigurationKey().IsOperationLabourRateConfigure === false) {
            if (el.value === 'LabourRate') return false;
        }
        if (getConfigurationKey().IsDestinationPlantConfigure === false) {
            if (el.value === 'DestinationPlant') return false;
            if (el.value === 'DestinationPlantCode') return false;
            if (el.value === 'PlantCode') return false;
        }

        if (getConfigurationKey().IsAutoGeneratedOperationCode === true) {
            if (el.value === 'OperationCode') return false;
        }
        if (getConfigurationKey().IsShowDetailedOperationBreakup === false) {
            const operationKeys = ['OperationType', 'WeldingRate', 'Consumption', 'Note'];
            if (operationKeys.includes(el.value)) return false;
        }
        return true;
    })
}
export const checkInterestRateConfigure = (excelData) => {
    return excelData.filter((el) => {
        if (getConfigurationKey().IsShowRawMaterialInOverheadProfitAndICC === false) {
            if (el.value === 'RawMaterialName') return false;
            if (el.value === 'RawMaterialGrade') return false;
        }
        return true;
    })
}
/**
* @method checkVendorPlantConfig
* @description CONDITION TO CHECK:- TO AVOID VENDOR PLANT IF NOT CONFIGURABLE FROM INITIALIZER
*/
export const checkVendorPlantConfig = (excelData, type = '', isBop = false, isVendor = false) => {





    return excelData.filter((el) => {
        if (checkVendorPlantConfigurable() === false) {
            if (el.value === 'VendorPlant') return false;
            /**********************DON'T REMOVE NOW MAY BE USED LATER**********************************/
            // if (el.value === 'LabourRate') return false;
            // if (el.value === 'VendorName') return false;
            // if (el.value === 'VendorPlantCode') return false;
            // if (el.value === 'DestinationPlant') return false;
            // if (el.value === 'DestinationPlantCode') return false;

        }
        if (IsShowFreightAndShearingCostFields() === false) {
            const freightAndShearingCostKeys = ['FreightCost', 'ShearingCost', 'RMFreightCost', 'RMShearingCost', 'RawMaterialFreightCostConversion', 'RawMaterialShearingCostConversion '];
            if (freightAndShearingCostKeys.includes(el.value)) return false;
        }
        if (getConfigurationKey().IsAutoGeneratedMachineNumber && el.value === 'MachineNo') return false;
        if (getConfigurationKey().IsAutoGeneratedRawMaterialCode && el.value === 'RawMaterialCode') return false;
        if (getConfigurationKey().IsDestinationPlantConfigure === false) {
            if (el.value === 'DestinationPlant') return false;
            if (el.value === 'DestinationPlantCode') return false;
            if (el.value === 'PlantCode') return false;
        }
        if (getConfigurationKey().IsAutoGeneratedProcessCode === true) {
            if (el.value === 'ProcessCode') return false;
        }
        if (type === CBCTypeId && getConfigurationKey().IsCBCApplicableOnPlant === false) {
            if (el.value === 'DestinationPlantName') return false;
            if (el.value === 'DestinationPlantCode') return false;
            if (el.value === 'PlantCode') return false;
        }
        if (getConfigurationKey().IsShowClientVendorBOP === false) {
            if (el.value === 'IsClientVendorBOP') return false;
        }
        if (isBop && getConfigurationKey().IsBoughtOutPartCostingConfigured === false) {
            if (el.value === 'IsBreakupBoughtOutPart') return false;
            if (el.value === 'TechnologyName') return false;
        }
        if (getConfigurationKey().IsMinimumOrderQuantityVisible === false) {
            if (el.value === 'NumberOfPieces') return false;
        }
        if (isVendor && !getConfigurationKey().IsCriticalVendorConfigured) {
            if (el.value === "IsCriticalVendor") return false;
            if (el.value === "Technology") return false;
            if (el.value === "PlantCode") return false;
        }
        if (getConfigurationKey().IsAutoGeneratedBOPNumber === true) {
            if (el.value === `${showBopLabel()}Number`) return false;
        }
        if (getConfigurationKey().IsShowPaymentTermsFields === false) {
            if (el.value === 'PaymentTerm') return false;
        }
        if (getConfigurationKey().IsSAPConfigured === false) {
            if (el.value === 'SAPCode') return false;
        }
        return true;
    })
}
class Downloadxls extends React.Component {
    /**
    * @method renderSwitch
    * @description Switch case for different xls file head according to master
    */
    renderSwitch = (master) => {

        let updatedLabels
        const { selectedOption } = this.props

        switch (master) {
            case 'RM Specification':
                return this.returnExcelColumn(checkRM_Process_OperationConfigurable(RMSpecification), RMSpecificationXLTempData);
            case 'Vendor':
                ({ updatedLabels } = updateBOPValues(Vendor, VendorTempData, bopMasterName, 'label'));

                return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', false, true), VendorTempData);
            case 'Overhead':
                return this.returnExcelColumn(Overhead, OverheadTempData);
            case 'Index Data':
                return this.returnExcelColumn(IndexDataListing, IndexDataListingTempData);
            case 'Index':
                return this.returnExcelColumn(IndexCommodityListing, IndexCommodityListingTempData);
            case 'Commodity (In Index)':
                return this.returnExcelColumn(CommodityInIndexListing, CommodityInIndexListingTempData);
            case 'Commodity Standardization':
                return this.returnExcelColumn(StandardizedCommodityNameListing, StandardizedCommodityNameTempData);
            case 'Commodity Standard':
                return this.returnExcelColumn(CommodityStandard, CommodityStandardTempData);
            case 'Fuel':
                return this.returnExcelColumn(Fuel, FuelTempData);
            case 'Profit':
                return this.returnExcelColumn(Profit, ProfitTempData);
            case 'Labour':
                return this.returnExcelColumn(Labour, LabourTempData);
            case 'Part Component':
                return this.returnExcelColumn(checkSAPCodeinExcel(withLocalization(PartComponent, this.props.t, "MasterLabels")), checkSAPCodeinExcel(PartComponentTempData));
            case 'Product Component':
                return this.returnExcelColumn(ProductComponent, ProductComponentTempData);
            case 'BOM':
                return this.returnExcelColumn(withLocalization(BOMUpload, this.props.t, "MasterLabels"), BOMUploadTempData);


            case BOUGHTOUTPARTSRFQ:
                return this.returnExcelColumn(AddBoughtOutPartsHeaderData, AddBoughtOutPartsTempData);
            case RAWMATERIALSRFQ:
                return this.returnExcelColumn(AddRawMaterialHeaderData, AddRawMaterialTempData);
            case ASSEMBLYORCOMPONENTSRFQ:
                return this.returnExcelColumn(AddAssemblyOrComponentHeaderData, AddAssemblyOrComponentTempData);





            //return this.returnExcelColumn(AddRFQUpload, AddRFQTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method renderZBCSwitch
    * @description Switch case for different xls file head according to master
    */

    renderZBCSwitch = (master) => {
        let updatedLabels
        switch (master) {
            case 'RM':
                if (!this.props.isImport) {
                    return this.returnExcelColumn(checkRM_Process_OperationConfigurable(withLocalization(RMDomesticZBC, this.props.t, "MasterLabels")), RMDomesticZBCTempData, true);
                } else {
                    return this.returnExcelColumn(checkRM_Process_OperationConfigurable(withLocalization(RMImportZBC, this.props.t, "MasterLabels")), RMImportZBCTempData);
                }
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(withLocalization(ZBCOperationSmallForm, this.props.t, "MasterLabels")), ZBCOperationTempData, true);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(MachineZBC, this.props.t, "MasterLabels")), MachineZBCTempData);
            case ZBCADDMORE:
            case VBCADDMORE:
            case CBCADDMORE:
                return this.returnExcelColumn(checkRM_Process_OperationConfigurable(withLocalization(MHRMoreZBC, this.props.t, "MasterLabels")), MHRMoreZBCTempData);
            case `${showBopLabel()} Domestic`:
                ({ updatedLabels } = updateBOPValues(BOP_ZBC_DOMESTIC, BOP_ZBC_DOMESTIC_TempData, bopMasterName, 'label'));
                return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_ZBC_DOMESTIC_TempData);
            case `${showBopLabel()} Import`:
                ({ updatedLabels } = updateBOPValues(BOP_ZBC_IMPORT, BOP_ZBC_IMPORT_TempData, bopMasterName, 'label'));
                return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_ZBC_IMPORT_TempData);

            case `Overhead`:

                return this.returnExcelColumn(Overhead, OverheadTempData);
            case `Profit`:

                return this.returnExcelColumn(Profit, ProfitTempData);
            case 'Actual Volume':
                return this.returnExcelColumn(VOLUME_ACTUAL_ZBC, VOLUME_ACTUAL_ZBC_TEMPDATA);
            case 'Budgeted Volume':
                return this.returnExcelColumn(VOLUME_BUDGETED_ZBC, VOLUME_BUDGETED_ZBC_TEMPDATA);
            case 'Interest Rate':
                return this.returnExcelColumn(ZBCInterestRate, ZBCInterestRateTempData);
            case 'Budget':
                return this.returnExcelColumn(BUDGET_ZBC, BUDGET_ZBC_TEMPDATA);
            case 'Labour':
                return this.returnExcelColumn(Labour, LabourTempData);
            case ZBCADDMOREOPERATION:
                return this.returnExcelColumn(withLocalization(ZBCOperation, this.props.t, "MasterLabels"), ZBCOperationTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method renderVBCSwitch
    * @description Switch case for different xls file head according to master
    */
    renderVBCSwitch = (master, bopType) => {
        let updatedLabels;
        switch (master) {
            case 'RM':
                if (!this.props.isImport) {
                    return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(RMDomesticVBC, this.props.t, "MasterLabels")), RMDomesticVBCTempData, true);
                } else {
                    return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(RMDomesticVBC, this.props.t, "MasterLabels")), RMImportVBCTempData);
                }
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(withLocalization(VBCOperationSmallForm, this.props.t, "MasterLabels")), VBCOperationTempData, true);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(MachineVBC, this.props.t, "MasterLabels")), MachineVBCTempData);
            case `${showBopLabel()} Domestic`:
                if (bopType === DETAILED_BOP) {
                    ({ updatedLabels } = updateBOPValues(withLocalization(BOP_DETAILED_DOMESTIC, this.props.t, "MasterLabels"), [], bopMasterName, 'label'));

                    return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_DETAILED_DOMESTIC_TempData);
                } else {
                    ({ updatedLabels } = updateBOPValues(BOP_VBC_DOMESTIC, [], bopMasterName, 'label'));

                    return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_VBC_DOMESTIC_TempData);
                }
            case `${showBopLabel()} Import`:
                if (bopType === DETAILED_BOP) {
                    ({ updatedLabels } = updateBOPValues(withLocalization(BOP_DETAILED_IMPORT, this.props.t, "MasterLabels"), [], bopMasterName, 'label'));

                    return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_DETAILED_IMPORT_TempData);
                } else {
                    ({ updatedLabels } = updateBOPValues(BOP_VBC_IMPORT, [], bopMasterName, 'label'));

                    return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, '', true), BOP_VBC_IMPORT_TempData);
                }
            case `Overhead`:

                return this.returnExcelColumn(OverheadVBC, OverheadVBC_TempData);
            case `Profit`:

                return this.returnExcelColumn(ProfitVBC, ProfitTempDataVBC);
            case 'Actual Volume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_ACTUAL_VBC), VOLUME_ACTUAL_VBC_TEMPDATA);
            case 'Budgeted Volume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_BUDGETED_VBC), VOLUME_BUDGETED_VBC_TEMPDATA);
            case 'Interest Rate':
                return this.returnExcelColumn(checkInterestRateConfigure(VBCInterestRate), VBCInterestRateTempData);
            case 'Budget':
                return this.returnExcelColumn(BUDGET_VBC, BUDGET_VBC_TEMPDATA);
            case 'Labour':
                return this.returnExcelColumn(Labour, LabourTempData);
            case VBCADDMOREOPERATION:
                return this.returnExcelColumn(withLocalization(VBCOperation, this.props.t, "MasterLabels"), VBCOperationTempData);
            default:
                return 'foo';
        }
    }
    /**
     * @method renderVBCSwitch
     * @description Switch case for different xls file head according to master
     */
    renderCBCSwitch = (master) => {
        let updatedLabels;
        switch (master) {
            case 'RM':
                if (!this.props.isImport) {
                    return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(RMDomesticCBC, this.props.t, "MasterLabels"), CBCTypeId), RMDomesticCBCTempData, true);
                } else {
                    return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(RMImportCBC, this.props.t, "MasterLabels"), CBCTypeId), RMImportCBCTempData);
                }
            case 'Operation':
                return this.returnExcelColumn(checkLabourRateConfigure(withLocalization(CBCOperationSmallForm, this.props.t, "MasterLabels")), CBCOperationTempData, true);
            case 'Machine':
                return this.returnExcelColumn(checkVendorPlantConfig(withLocalization(MachineCBC, this.props.t, "MasterLabels"), CBCTypeId), MachineCBCTempData);
            case `${showBopLabel()} Domestic`:
                ({ updatedLabels } = updateBOPValues(BOP_CBC_DOMESTIC, [], bopMasterName, 'label'));

                return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, CBCTypeId, true), BOP_CBC_DOMESTIC_TempData);
            case `${showBopLabel()} Import`:
                ({ updatedLabels } = updateBOPValues(BOP_CBC_IMPORT, [], bopMasterName, 'label'));

                return this.returnExcelColumn(checkVendorPlantConfig(updatedLabels, CBCTypeId, true), BOP_CBC_IMPORT_TempData);
            case `Overhead`:

                return this.returnExcelColumn(OverheadCBC, OverheadCBC_TempData);
            case `Profit`:
                return this.returnExcelColumn(ProfitCBC, ProfitTempDataCBC);
            case 'Actual Volume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_ACTUAL_CBC, CBCTypeId), VOLUME_ACTUAL_CBC_TEMPDATA);
            case 'Budgeted Volume':
                return this.returnExcelColumn(checkVendorPlantConfig(VOLUME_BUDGETED_CBC, CBCTypeId), VOLUME_BUDGETED_CBC_TEMPDATA);
            case 'Interest Rate':
                return this.returnExcelColumn(checkInterestRateConfigure(CBCInterestRate), CBCInterestRateTempData);
            case 'Budget':
                return this.returnExcelColumn(BUDGET_CBC, BUDGET_CBC_TEMPDATA);
            case 'Labour':
                return this.returnExcelColumn(Labour, LabourTempData);
            case CBCADDMOREOPERATION:
                return this.returnExcelColumn(withLocalization(CBCOperation, this.props.t, "MasterLabels"), CBCOperationTempData);
            default:
                return 'foo';
        }
    }

    /**
    * @method returnExcelColumn
    * @description Used to get excel column names
    */
    returnExcelColumn = (data = [], TempData, isNoteColExist = false) => {
        const { fileName, failedData, isFailedFlag } = this.props;

        let dataList = [...data]


        if (isFailedFlag) {
            //BELOW CONDITION TO ADD 'REASON' COLUMN WHILE DOWNLOAD EXCEL SHEET IN CASE OF FAILED
            let isContentReason = dataList.filter(d => d.label === 'Reason')
            if (isContentReason.length === 0) {
                let addObj = { label: 'Reason', value: 'Reason' }
                dataList.push(addObj)
            }
        }
        // Replace labels based on the file name containing "BOP domestic" or "BOP import"

        if (isNoteColExist && failedData) {
            const notesInTemp = TempData.some(item => item.Note)
            const notesInFailed = failedData.some(item => item.Note);
            if (notesInTemp && !notesInFailed) {
                // Add Notes from TempData to failedData
                for (let i = 0; i < failedData.length && i < TempData.length; i++) {
                    failedData[i].Note = TempData[i].Note || failedData[i].Note;
                }
            }
        }

        return (<ExcelSheet data={isFailedFlag ? failedData : TempData} name={fileName}>

            {dataList && dataList.map((ele, index) => <ExcelColumn key={index} label={ele.label} value={ele.value} style={ele.style} />)}
        </ExcelSheet>);
    }

    render() {
        const { isFailedFlag, fileName, isZBCVBCTemplate, isMachineMoreTemplate, costingTypeId, bopType } = this.props;
        const downloadFileName = (fileName === 'RM')
            ? (this.props.isImport ? 'RM Import' : 'RM Domestic')
            : fileName;
        // DOWNLOAD FILE:- CALLED WHEN ZBC FILE FAILED   hideElement={true}
        // ZBC_MACHINE_MORE THIS IS ADDITIONAL CONDITION ONLY FOR MACHINE MORE DETAIL FROM MACHINE MASTER
        if (isFailedFlag && (costingTypeId === ZBCTypeId || costingTypeId === ZBCADDMOREOPERATION) && (fileName === 'RM' || fileName === 'Operation' || fileName === 'Machine' || fileName === `${showBopLabel()} Domestic` || fileName === `${showBopLabel()} Import` || fileName === 'Actual Volume' || fileName === 'Budgeted Volume' || fileName === 'Interest Rate' || fileName === 'Budget')) {
            return (
                <ExcelFile hideElement={true} filename={`${downloadFileName} ZBC`} fileExtension={'.xls'} >
                    {isMachineMoreTemplate || costingTypeId === ZBCADDMOREOPERATION ? this.renderZBCSwitch(costingTypeId) : this.renderZBCSwitch(fileName)}
                </ExcelFile>
            );
        }
        if (isFailedFlag && (costingTypeId === ZBCADDMORE || costingTypeId === VBCADDMORE || costingTypeId === CBCADDMORE) && (fileName === 'Machine')) {

            return (
                <ExcelFile hideElement={true} filename={"Add more details"} fileExtension={'.xls'} >
                    {isMachineMoreTemplate || (costingTypeId === ZBCADDMORE || costingTypeId === VBCADDMORE || costingTypeId === CBCADDMORE) ? this.renderZBCSwitch(costingTypeId) : ""}
                </ExcelFile>
            );
        }

        // DOWNLOAD FILE:- CALLED WHEN VBC FILE FAILED
        if (isFailedFlag && (costingTypeId === VBCTypeId || costingTypeId === VBCADDMOREOPERATION || bopType === DETAILED_BOP) && (fileName === 'RM' || fileName === 'Operation' || fileName === 'Machine' || fileName === `${showBopLabel()} Domestic` || fileName === `${showBopLabel()} Import` || fileName === 'Actual Volume' || fileName === 'Budgeted Volume' || fileName === 'Interest Rate' || fileName === 'Budget')) {

            return (
                <ExcelFile hideElement={true} filename={`${downloadFileName}VBC`} fileExtension={'.xls'} >
                    {costingTypeId === VBCADDMOREOPERATION ? this.renderVBCSwitch(costingTypeId) : this.renderVBCSwitch(fileName, bopType)}
                </ExcelFile>
            );
        }
        // DOWNLOAD FILE:- CALLED WHEN CBC FILE FAILED
        if (isFailedFlag && (costingTypeId === CBCTypeId || costingTypeId === CBCADDMOREOPERATION) && (fileName === 'RM' || fileName === 'Operation' || fileName === 'Machine' || fileName === `${showBopLabel()} Domestic` || fileName === `${showBopLabel()} Import` || fileName === 'Actual Volume' || fileName === 'Budgeted Volume' || fileName === 'Interest Rate' || fileName === 'Budget')) {

            return (
                <ExcelFile hideElement={true} filename={`${downloadFileName} CBC`} fileExtension={'.xls'} >
                    {costingTypeId === CBCADDMOREOPERATION ? this.renderCBCSwitch(costingTypeId) : this.renderCBCSwitch(fileName)}
                </ExcelFile>
            );
        }
        // DOWNLOAD FILE:- CALLED WHEN FILE FAILED APART FROM ZBC AND VBC
        if (isFailedFlag && (fileName === 'RM Specification' || fileName === 'Vendor' || fileName === 'Overhead' || fileName === 'Fuel' || fileName === 'Labour' || fileName === 'Part Component' || fileName === 'Product Component' || fileName === ASSEMBLYORCOMPONENTSRFQ || fileName === BOUGHTOUTPARTSRFQ || fileName === RAWMATERIALSRFQ || fileName === 'Index' || fileName === 'Index Data' || fileName === 'Commodity (In Index)' || fileName === 'Commodity Standard' || fileName === 'Commodity Standardization')) {

            return (
                <ExcelFile hideElement={true} filename={fileName} fileExtension={'.xls'} >
                    {this.renderSwitch(fileName)}
                </ExcelFile>
            );
        }

        // DISPLAY RADIO BUTTON ZBC AND VBC, WITH FILE DOWNLOAD BUTTON
        if (isZBCVBCTemplate) {
            return (
                <>
                    {(costingTypeId === ZBCTypeId || costingTypeId === ZBCADDMOREOPERATION) &&
                        <ExcelFile filename={costingTypeId === ZBCADDMOREOPERATION ? 'ZBC More Details' : `${downloadFileName} ZBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download ZBC</button>}>
                            {costingTypeId !== ZBCADDMOREOPERATION ? this.renderZBCSwitch(fileName) : this.renderZBCSwitch(costingTypeId)}
                        </ExcelFile>}

                    {(costingTypeId === VBCTypeId || costingTypeId === VBCADDMOREOPERATION) &&
                        <ExcelFile filename={costingTypeId === VBCADDMOREOPERATION ? 'VBC More Details' : `${downloadFileName} VBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download VBC</button>}>

                            {(costingTypeId === VBCADDMOREOPERATION ? this.renderVBCSwitch(Number(costingTypeId)) : this.renderVBCSwitch(fileName))}
                        </ExcelFile>}
                    {(costingTypeId === CBCTypeId || costingTypeId === CBCADDMOREOPERATION) &&
                        <ExcelFile filename={costingTypeId === CBCADDMOREOPERATION ? 'CBC More Details' : `${downloadFileName} CBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download CBC</button>}>
                            {costingTypeId !== CBCADDMOREOPERATION ? this.renderCBCSwitch(fileName) : this.renderCBCSwitch(costingTypeId)}
                        </ExcelFile>}
                    {bopType === DETAILED_BOP &&
                        <ExcelFile filename={`${fileName} VBC`} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download VBC Detailed {showBopLabel()}</button>}>
                            {fileName ? this.renderVBCSwitch(fileName, bopType) : ''}
                        </ExcelFile>}
                    {/* ZBC_MACHINE_MORE THIS IS ADDITIONAL CONDITION ONLY FOR MACHINE MORE DETAIL FROM MACHINE MASTER */}
                    {(costingTypeId === ZBCADDMORE || costingTypeId === VBCADDMORE || costingTypeId === CBCADDMORE) &&
                        <ExcelFile filename={"Add more details"} fileExtension={'.xls'} element={<button type="button" className={'btn btn-primary pull-right w-100'}><div class="download"></div> Download More DETAIL</button>}>
                            {fileName ? this.renderZBCSwitch(costingTypeId) : ''}
                        </ExcelFile >}
                </>
            );
        }

        // DISPLAY DOWNLOAD FILE BUTTON EXCEPT ZBC AND VBC TEMPLATES
        return (
            <ExcelFile filename={fileName} fileExtension={'.xls'} element={< button type="button" className={'btn btn-primary pull-right w-100'} > <div class="download"></div> Download File</button>}>
                {fileName ? this.renderSwitch(fileName) : ''}
            </ExcelFile >
        );
    }
}

export default withTranslation('MasterLabels')(Downloadxls);