export const viewCostingData = [
    {
        assemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        BasicRate: 2600,
        BudgetedPrice: 0,
        BudgetedPriceVariance: 2600,
        BurningLossWeight: null,
        CostingHeading: "",
        CostingMasterBatchRawMaterialCostResponse: [],
        CostingNumber: "SHM-2131",
        CostingPartDetails: {
            IsRMCutOffApplicable: false,
            CostingDetailId: '753a89cb-1743-4689-90c9-12b8768f1444',
            PartId: 'ff780175-fc48-4760-b68d-08a21e606784',
            PartTypeId: 2,
            Type: 'Component',
            DiscountCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                CRMHead: "",
                Description: "",
                NetCost: 0,
                Type: "Discount",
                Value: null,

            }]
        },
        ForgingScrapWeight: null,
        ICCRemark: "-",
        IsApprovalLocked: false,
        IsAssemblyCosting: "",
        IsRegularized: "",
        IsScrapRecoveryPercentageApplied: null,
        IsShowCheckBoxForApproval: true,
        MachiningScrapRate: null,
        MachiningScrapWeight: null,
        NCCPartQuantity: "",
        OverheadRemark: "-",
        PaymentTermRemark: "-",
        PoPriceWithDate: "2600 (03-04-2024)",
        ProfitApplicablity: "-",
        ProfitApplicablityValue: 0,
        ProfitRemark: "-",
        RawMaterialCalculatorId: 0,
        RejectionRemark: "-",
        RevisionNumber: "-",
        ScrapRecoveryPercentage: 0,
        ScrapWeight: 55,
        SubAssemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        aValue: {
            applicability: 'Applicability',
            percentage: 'Percentage (%)',
            value: 'Value'
        },
        amortizationQty: 0,
        anyOtherCost: undefined,
        anyOtherCostApplicablity: undefined,
        anyOtherCostPercent: undefined,
        anyOtherCostTotal: "-",
        anyOtherCostType: undefined,
        approvalButton: "",
        attachment: [
            // Attachments data here
        ],
        bopHandlingChargeType: "",
        bopHandlingPercentage: 0,
        bopPHandlingCharges: 0,
        castingWeight: null,
        castingWeightExcel: 0,
        childPartBOPHandlingCharges: [],
        conditionCost: 0,
        costingDate: "2024-04-11T14:43:39.96",
        costingHead: "VBC",
        costingHeadCheck: "VBC",
        costingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        costingName: "SHM-2131-04-11-2024-Returned",
        costingTypeId: 2,
        costingVersion: "11-04-2024-SHM-2131",
        currency: { currencyTitle: '-', currencyValue: '-' },
        currencyRate: "-",
        currencyTitle: "-",
        customer: "-",
        customerCode: "",
        customerId: "00000000-0000-0000-0000-000000000000",
        customerName: "",
        destinationPlantCode: "BhuPlantOne",
        destinationPlantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        destinationPlantName: "BhuPlantOne (1569)",
        effectiveDate: "2024-04-03T00:00:00",
        fWeight: 5,
        freight: 0,
        gWeight: 60,
        getApprovalLockedMessage: "",
        iccApplicablity: "-",
        iccApplicablityValue: 0,
        iccOn: { iccTitle: '-', iccValue: 0, iccPercentage: '-', ICCCRMHead: '-', ICCRemark: '-' },
        iccPercent: "-",
        isApplyMasterBatch: false,
        isIncludeOverheadAndProfitInICC: null,
        isIncludeSurfaceTreatmentWithOverheadAndProfit: null,
        isIncludeSurfaceTreatmentWithRejection: null,
        isIncludeToolCostInCCForICC: null,
        isIncludeToolCostWithOverheadAndProfit: null,
        isRFQFinalApprovedCosting: false,
        isRmCutOffApplicable: false,
        isToolCostProcessWise: undefined,
        lineNumber: "-",
        masterBatchPercentage: 0,
        masterBatchRMName: "-",
        masterBatchRMPrice: 0,
        masterBatchTotal: 0,
        meltingLoss: "null (null%)",
        meltingLossExcel: "0 (0%)",
        modelType: "-",
        multiTechnologyCostingDetails: "",
        nConvCost: 0,
        nOverheadProfit: 0,
        nPOPrice: 2600,
        nPOPriceWithCurrency: 0,
        nPackagingAndFreight: 0,
        nPoPriceCurrency: 2600,
        nTotalRMBOPCC: 2600,
        netBOP: 0,
        netBOPCostView: [],
        netBoughtOutPartCost: 0,
        netChildPartsCost: 0,
        netConditionCost: 0,
        netConversionCostView: { IsShowToolCost: false, NetProcessCost: 0, NetOperationCost: 0, NetOtherOperationCost: null, ToolsCostTotal: null },
        netFreightCostView: [],
        netNpvCost: 0,
        netLineInvestmentCost: 0,
        netOperationCost: 0,
        netOtherOperationCost: 0,
        netOverheadCostView: { OverheadDetailId: null, OverheadId: null, IsOverheadCombined: null, OverheadApplicabilityId: null, OverheadApplicability: null },
        netPackagingCostView: [],
        netPaymentIccCostView: { NetICC: 0, NetPaymentTermCost: 0, IsInventoryCarringCost: null, IsPaymentTerms: null, ICCApplicabilityDetail: null },
        netProcessCost: 0,
        netProfitCostView: { ProfitId: null, ProfitDetailId: null, ProfitApplicabilityId: null, ProfitApplicability: null, IsProfitCombined: null, },
        netRM: 2600,
        netRMCostView: [],
        netRejectionCostView: { RejectionDetailId: null, RejectionApplicabilityId: null, RejectionApplicability: null, RejectionPercentage: null, RejectionCost: null },
        netSurfaceTreatmentCost: 0,
        netToolCostView: [],
        netTransportationCostView: [],
        npvCost: 0,
        nsTreamnt: 0,
        oCost: 0,
        oldPoPrice: 0,
        otherDiscount: { discount: 'Discount %', value: 'Value' },
        otherDiscountApplicablity: null,
        otherDiscountCost: 0,
        otherDiscountType: undefined,
        otherDiscountValue: { discountPercentValue: undefined, discountValue: undefined, discountApplicablity: undefined, dicountType: undefined },
        otherDiscountValuePercent: null,
        overHeadApplicablity: "-",
        overHeadApplicablityValue: 0,
        overHeadPercent: "-",
        overheadOn: { overheadTitle: '-', overheadValue: 0, overheadPercentage: '-', overheadRMPercentage: '-', overheadBOPPercentage: '-' },
        pCost: 0,
        packagingCost: 0,
        partId: "ff780175-fc48-4760-b68d-08a21e606784",
        partName: "Part-RFQ-004",
        partNumber: "Part-RFQ-004",
        partType: "Component",
        partTypeId: 2,
        paymentApplicablity: "-",
        paymentPercent: "-",
        paymentTerms: { paymentTitle: '-', paymentValue: 0, paymentPercentage: '-', PaymentTermCRMHead: '-', PaymentTermRemark: '-' },
        paymentcApplicablityValue: 0,
        plantCode: "BhuPlantOne",
        plantExcel: "BhuPlantOne (1569)",
        plantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        plantName: "BhuPlantOne (1569)",
        poPrice: 2600,
        profitOn: { profitTitle: '-', profitValue: 0, profitPercentage: '-', profitRMPercentage: '-', profitBOPPercentage: '-' },
        profitPercent: "-",
        rawMaterialCostWithCutOff: 2600,
        rejectionApplicablity: "-",
        rejectionApplicablityValue: 0,
        rejectionOn: { rejectionTitle: '-', rejectionValue: 0, rejectionPercentage: '-', RejectionCRMHead: '-', RejectionRemark: '-' },
        rejectionPercent: "-",
        remark: "-",
        rm: "RM-15691 - RM",
        rmRate: 80,
        sTreatment: 0,
        saNumber: "-",
        scrapRate: 40,
        shareOfBusinessPercent: 0,
        sobPercentageExcel: 0,
        status: "Returned",
        surfaceTreatmentDetails: [],
        tCost: 0,
        technology: "Sheet Metal",
        technologyId: 1,
        toolAmortizationCost: 0,
        toolApplicability: { applicability: 'Applicability', value: 'Value' },
        toolApplicabilityValue: { toolTitle: '-', toolValue: 0 },
        toolMaintenanceCost: 0,
        toolMaintenanceCostApplicablity: 0,
        toolMaintenanceCostApplicablityValue: 0,
        toolPrice: 0,
        totalCost: 2600,
        totalTabSum: 2600,
        totalToolCost: 0,
        vendor: "BhuVendorTwo (1568)",
        vendorCode: "1568",
        vendorExcel: "BhuVendorTwo (1568)",
        vendorId: "dad1a53b-1792-48c1-ad91-74dbc9dcc60b",
        vendorName: "BhuVendorTwo",
        vendorPlantCode: "-",
        vendorPlantId: "-",
        vendorPlantName: "-",
        zbc: 2,
        tco: true,
        tcoValues: {
            WarrantyYears: "3",
            QualityPPM: "5000",
            MOQ: "2",
            SPQ: "1",
            LeadTime: "-",
            UOM: "kg",
            AvailableCapacity: "-",
            IncoTerms: "-",
            PayTerms: "-",
            LdClause: "-",
            TotalCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                NetCost: 0,
                Years: 3,
                Days: 90


            }]
        }
    },
    {
        assemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        BasicRate: 2600,
        BudgetedPrice: 0,
        BudgetedPriceVariance: 2600,
        BurningLossWeight: null,
        CostingHeading: "",
        CostingMasterBatchRawMaterialCostResponse: [],
        CostingNumber: "SHM-2131",
        CostingPartDetails: {
            IsRMCutOffApplicable: false,
            CostingDetailId: '753a89cb-1743-4689-90c9-12b8768f1444',
            PartId: 'ff780175-fc48-4760-b68d-08a21e606784',
            PartTypeId: 2,
            Type: 'Component',
            DiscountCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                CRMHead: "",
                Description: "",
                NetCost: 0,
                Type: "Discount",
                Value: null,

            }]
        },
        ForgingScrapWeight: null,
        ICCRemark: "-",
        IsApprovalLocked: false,
        IsAssemblyCosting: "",
        IsRegularized: "",
        IsScrapRecoveryPercentageApplied: null,
        IsShowCheckBoxForApproval: true,
        MachiningScrapRate: null,
        MachiningScrapWeight: null,
        NCCPartQuantity: "",
        OverheadRemark: "-",
        PaymentTermRemark: "-",
        PoPriceWithDate: "2600 (03-04-2024)",
        ProfitApplicablity: "-",
        ProfitApplicablityValue: 0,
        ProfitRemark: "-",
        RawMaterialCalculatorId: 0,
        RejectionRemark: "-",
        RevisionNumber: "-",
        ScrapRecoveryPercentage: 0,
        ScrapWeight: 55,
        SubAssemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        aValue: {
            applicability: 'Applicability',
            percentage: 'Percentage (%)',
            value: 'Value'
        },
        amortizationQty: 0,
        anyOtherCost: undefined,
        anyOtherCostApplicablity: undefined,
        anyOtherCostPercent: undefined,
        anyOtherCostTotal: "-",
        anyOtherCostType: undefined,
        approvalButton: "",
        attachment: [
            // Attachments data here
        ],
        bopHandlingChargeType: "",
        bopHandlingPercentage: 0,
        bopPHandlingCharges: 0,
        castingWeight: null,
        castingWeightExcel: 0,
        childPartBOPHandlingCharges: [],
        conditionCost: 0,
        costingDate: "2024-04-11T14:43:39.96",
        costingHead: "VBC",
        costingHeadCheck: "VBC",
        costingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        costingName: "SHM-2131-04-11-2024-Returned",
        costingTypeId: 2,
        costingVersion: "11-04-2024-SHM-2131",
        currency: { currencyTitle: '-', currencyValue: '-' },
        currencyRate: "-",
        currencyTitle: "-",
        customer: "-",
        customerCode: "",
        customerId: "00000000-0000-0000-0000-000000000000",
        customerName: "",
        destinationPlantCode: "BhuPlantOne",
        destinationPlantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        destinationPlantName: "BhuPlantOne (1569)",
        effectiveDate: "2024-04-03T00:00:00",
        fWeight: 5,
        freight: 0,
        gWeight: 60,
        getApprovalLockedMessage: "",
        iccApplicablity: "-",
        iccApplicablityValue: 0,
        iccOn: { iccTitle: '-', iccValue: 0, iccPercentage: '-', ICCCRMHead: '-', ICCRemark: '-' },
        iccPercent: "-",
        isApplyMasterBatch: false,
        isIncludeOverheadAndProfitInICC: null,
        isIncludeSurfaceTreatmentWithOverheadAndProfit: null,
        isIncludeSurfaceTreatmentWithRejection: null,
        isIncludeToolCostInCCForICC: null,
        isIncludeToolCostWithOverheadAndProfit: null,
        isRFQFinalApprovedCosting: false,
        isRmCutOffApplicable: false,
        isToolCostProcessWise: undefined,
        lineNumber: "-",
        masterBatchPercentage: 0,
        masterBatchRMName: "-",
        masterBatchRMPrice: 0,
        masterBatchTotal: 0,
        meltingLoss: "null (null%)",
        meltingLossExcel: "0 (0%)",
        modelType: "-",
        multiTechnologyCostingDetails: "",
        nConvCost: 0,
        nOverheadProfit: 0,
        nPOPrice: 2600,
        nPOPriceWithCurrency: 0,
        nPackagingAndFreight: 0,
        nPoPriceCurrency: 2600,
        nTotalRMBOPCC: 2600,
        netBOP: 0,
        netBOPCostView: [],
        netBoughtOutPartCost: 0,
        netChildPartsCost: 0,
        netConditionCost: 0,
        netConversionCostView: { IsShowToolCost: false, NetProcessCost: 0, NetOperationCost: 0, NetOtherOperationCost: null, ToolsCostTotal: null },
        netFreightCostView: [],
        netNpvCost: 0,
        netLineInvestmentCost: 0,
        netOperationCost: 0,
        netOtherOperationCost: 0,
        netOverheadCostView: { OverheadDetailId: null, OverheadId: null, IsOverheadCombined: null, OverheadApplicabilityId: null, OverheadApplicability: null },
        netPackagingCostView: [],
        netPaymentIccCostView: { NetICC: 0, NetPaymentTermCost: 0, IsInventoryCarringCost: null, IsPaymentTerms: null, ICCApplicabilityDetail: null },
        netProcessCost: 0,
        netProfitCostView: { ProfitId: null, ProfitDetailId: null, ProfitApplicabilityId: null, ProfitApplicability: null, IsProfitCombined: null, },
        netRM: 2600,
        netRMCostView: [],
        netRejectionCostView: { RejectionDetailId: null, RejectionApplicabilityId: null, RejectionApplicability: null, RejectionPercentage: null, RejectionCost: null },
        netSurfaceTreatmentCost: 0,
        netToolCostView: [],
        netTransportationCostView: [],
        npvCost: 0,
        nsTreamnt: 0,
        oCost: 0,
        oldPoPrice: 0,
        otherDiscount: { discount: 'Discount %', value: 'Value' },
        otherDiscountApplicablity: null,
        otherDiscountCost: 0,
        otherDiscountType: undefined,
        otherDiscountValue: { discountPercentValue: undefined, discountValue: undefined, discountApplicablity: undefined, dicountType: undefined },
        otherDiscountValuePercent: null,
        overHeadApplicablity: "-",
        overHeadApplicablityValue: 0,
        overHeadPercent: "-",
        overheadOn: { overheadTitle: '-', overheadValue: 0, overheadPercentage: '-', overheadRMPercentage: '-', overheadBOPPercentage: '-' },
        pCost: 0,
        packagingCost: 0,
        partId: "ff780175-fc48-4760-b68d-08a21e606784",
        partName: "Part-RFQ-004",
        partNumber: "Part-RFQ-004",
        partType: "Component",
        partTypeId: 2,
        paymentApplicablity: "-",
        paymentPercent: "-",
        paymentTerms: { paymentTitle: '-', paymentValue: 0, paymentPercentage: '-', PaymentTermCRMHead: '-', PaymentTermRemark: '-' },
        paymentcApplicablityValue: 0,
        plantCode: "BhuPlantOne",
        plantExcel: "BhuPlantOne (1569)",
        plantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        plantName: "BhuPlantOne (1569)",
        poPrice: 2600,
        profitOn: { profitTitle: '-', profitValue: 0, profitPercentage: '-', profitRMPercentage: '-', profitBOPPercentage: '-' },
        profitPercent: "-",
        rawMaterialCostWithCutOff: 2600,
        rejectionApplicablity: "-",
        rejectionApplicablityValue: 0,
        rejectionOn: { rejectionTitle: '-', rejectionValue: 0, rejectionPercentage: '-', RejectionCRMHead: '-', RejectionRemark: '-' },
        rejectionPercent: "-",
        remark: "-",
        rm: "RM-15691 - RM",
        rmRate: 80,
        sTreatment: 0,
        saNumber: "-",
        scrapRate: 40,
        shareOfBusinessPercent: 0,
        sobPercentageExcel: 0,
        status: "Returned",
        surfaceTreatmentDetails: [],
        tCost: 0,
        technology: "Sheet Metal",
        technologyId: 1,
        toolAmortizationCost: 0,
        toolApplicability: { applicability: 'Applicability', value: 'Value' },
        toolApplicabilityValue: { toolTitle: '-', toolValue: 0 },
        toolMaintenanceCost: 0,
        toolMaintenanceCostApplicablity: 0,
        toolMaintenanceCostApplicablityValue: 0,
        toolPrice: 0,
        totalCost: 2600,
        totalTabSum: 2600,
        totalToolCost: 0,
        vendor: "BhuVendorTwo (1568)",
        vendorCode: "1568",
        vendorExcel: "BhuVendorTwo (1568)",
        vendorId: "dad1a53b-1792-48c1-ad91-74dbc9dcc60b",
        vendorName: "BhuVendorTwo",
        vendorPlantCode: "-",
        vendorPlantId: "-",
        vendorPlantName: "-",
        zbc: 2,
        tco: true,
        tcoValues: {
            WarrantyYears: "3",
            QualityPPM: "5000",
            MOQ: "2",
            SPQ: "1",
            LeadTime: "-",
            UOM: "kg",
            AvailableCapacity: "-",
            IncoTerms: "-",
            PayTerms: "-",
            LdClause: "-",
            TotalCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                NetCost: 0,
                Years: 3,
                Days: 90


            }]
        }
    },
    {
        assemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        BasicRate: 2600,
        BudgetedPrice: 0,
        BudgetedPriceVariance: 2600,
        BurningLossWeight: null,
        CostingHeading: "",
        CostingMasterBatchRawMaterialCostResponse: [],
        CostingNumber: "SHM-2131",
        CostingPartDetails: {
            IsRMCutOffApplicable: false,
            CostingDetailId: '753a89cb-1743-4689-90c9-12b8768f1444',
            PartId: 'ff780175-fc48-4760-b68d-08a21e606784',
            PartTypeId: 2,
            Type: 'Component',
            DiscountCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                CRMHead: "",
                Description: "",
                NetCost: 0,
                Type: "Discount",
                Value: null,

            }]
        },
        ForgingScrapWeight: null,
        ICCRemark: "-",
        IsApprovalLocked: false,
        IsAssemblyCosting: "",
        IsRegularized: "",
        IsScrapRecoveryPercentageApplied: null,
        IsShowCheckBoxForApproval: true,
        MachiningScrapRate: null,
        MachiningScrapWeight: null,
        NCCPartQuantity: "",
        OverheadRemark: "-",
        PaymentTermRemark: "-",
        PoPriceWithDate: "2600 (03-04-2024)",
        ProfitApplicablity: "-",
        ProfitApplicablityValue: 0,
        ProfitRemark: "-",
        RawMaterialCalculatorId: 0,
        RejectionRemark: "-",
        RevisionNumber: "-",
        ScrapRecoveryPercentage: 0,
        ScrapWeight: 55,
        SubAssemblyCostingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        aValue: {
            applicability: 'Applicability',
            percentage: 'Percentage (%)',
            value: 'Value'
        },
        amortizationQty: 0,
        anyOtherCost: undefined,
        anyOtherCostApplicablity: undefined,
        anyOtherCostPercent: undefined,
        anyOtherCostTotal: "-",
        anyOtherCostType: undefined,
        approvalButton: "",
        attachment: [
            // Attachments data here
        ],
        bopHandlingChargeType: "",
        bopHandlingPercentage: 0,
        bopPHandlingCharges: 0,
        castingWeight: null,
        castingWeightExcel: 0,
        childPartBOPHandlingCharges: [],
        conditionCost: 0,
        costingDate: "2024-04-11T14:43:39.96",
        costingHead: "VBC",
        costingHeadCheck: "VBC",
        costingId: "1e4b7966-2c76-4b13-9693-12554ee45759",
        costingName: "SHM-2131-04-11-2024-Returned",
        costingTypeId: 2,
        costingVersion: "11-04-2024-SHM-2131",
        currency: { currencyTitle: '-', currencyValue: '-' },
        currencyRate: "-",
        currencyTitle: "-",
        customer: "-",
        customerCode: "",
        customerId: "00000000-0000-0000-0000-000000000000",
        customerName: "",
        destinationPlantCode: "BhuPlantOne",
        destinationPlantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        destinationPlantName: "BhuPlantOne (1569)",
        effectiveDate: "2024-04-03T00:00:00",
        fWeight: 5,
        freight: 0,
        gWeight: 60,
        getApprovalLockedMessage: "",
        iccApplicablity: "-",
        iccApplicablityValue: 0,
        iccOn: { iccTitle: '-', iccValue: 0, iccPercentage: '-', ICCCRMHead: '-', ICCRemark: '-' },
        iccPercent: "-",
        isApplyMasterBatch: false,
        isIncludeOverheadAndProfitInICC: null,
        isIncludeSurfaceTreatmentWithOverheadAndProfit: null,
        isIncludeSurfaceTreatmentWithRejection: null,
        isIncludeToolCostInCCForICC: null,
        isIncludeToolCostWithOverheadAndProfit: null,
        isRFQFinalApprovedCosting: false,
        isRmCutOffApplicable: false,
        isToolCostProcessWise: undefined,
        lineNumber: "-",
        masterBatchPercentage: 0,
        masterBatchRMName: "-",
        masterBatchRMPrice: 0,
        masterBatchTotal: 0,
        meltingLoss: "null (null%)",
        meltingLossExcel: "0 (0%)",
        modelType: "-",
        multiTechnologyCostingDetails: "",
        nConvCost: 0,
        nOverheadProfit: 0,
        nPOPrice: 2600,
        nPOPriceWithCurrency: 0,
        nPackagingAndFreight: 0,
        nPoPriceCurrency: 2600,
        nTotalRMBOPCC: 2600,
        netBOP: 0,
        netBOPCostView: [],
        netBoughtOutPartCost: 0,
        netChildPartsCost: 0,
        netConditionCost: 0,
        netConversionCostView: { IsShowToolCost: false, NetProcessCost: 0, NetOperationCost: 0, NetOtherOperationCost: null, ToolsCostTotal: null },
        netFreightCostView: [],
        netNpvCost: 0,
        netLineInvestmentCost: 0,
        netOperationCost: 0,
        netOtherOperationCost: 0,
        netOverheadCostView: { OverheadDetailId: null, OverheadId: null, IsOverheadCombined: null, OverheadApplicabilityId: null, OverheadApplicability: null },
        netPackagingCostView: [],
        netPaymentIccCostView: { NetICC: 0, NetPaymentTermCost: 0, IsInventoryCarringCost: null, IsPaymentTerms: null, ICCApplicabilityDetail: null },
        netProcessCost: 0,
        netProfitCostView: { ProfitId: null, ProfitDetailId: null, ProfitApplicabilityId: null, ProfitApplicability: null, IsProfitCombined: null, },
        netRM: 2600,
        netRMCostView: [],
        netRejectionCostView: { RejectionDetailId: null, RejectionApplicabilityId: null, RejectionApplicability: null, RejectionPercentage: null, RejectionCost: null },
        netSurfaceTreatmentCost: 0,
        netToolCostView: [],
        netTransportationCostView: [],
        npvCost: 0,
        nsTreamnt: 0,
        oCost: 0,
        oldPoPrice: 0,
        otherDiscount: { discount: 'Discount %', value: 'Value' },
        otherDiscountApplicablity: null,
        otherDiscountCost: 0,
        otherDiscountType: undefined,
        otherDiscountValue: { discountPercentValue: undefined, discountValue: undefined, discountApplicablity: undefined, dicountType: undefined },
        otherDiscountValuePercent: null,
        overHeadApplicablity: "-",
        overHeadApplicablityValue: 0,
        overHeadPercent: "-",
        overheadOn: { overheadTitle: '-', overheadValue: 0, overheadPercentage: '-', overheadRMPercentage: '-', overheadBOPPercentage: '-' },
        pCost: 0,
        packagingCost: 0,
        partId: "ff780175-fc48-4760-b68d-08a21e606784",
        partName: "Part-RFQ-004",
        partNumber: "Part-RFQ-004",
        partType: "Component",
        partTypeId: 2,
        paymentApplicablity: "-",
        paymentPercent: "-",
        paymentTerms: { paymentTitle: '-', paymentValue: 0, paymentPercentage: '-', PaymentTermCRMHead: '-', PaymentTermRemark: '-' },
        paymentcApplicablityValue: 0,
        plantCode: "BhuPlantOne",
        plantExcel: "BhuPlantOne (1569)",
        plantId: "7c8c7b6b-5b4e-4127-8214-87e5626ed38a",
        plantName: "BhuPlantOne (1569)",
        poPrice: 2600,
        profitOn: { profitTitle: '-', profitValue: 0, profitPercentage: '-', profitRMPercentage: '-', profitBOPPercentage: '-' },
        profitPercent: "-",
        rawMaterialCostWithCutOff: 2600,
        rejectionApplicablity: "-",
        rejectionApplicablityValue: 0,
        rejectionOn: { rejectionTitle: '-', rejectionValue: 0, rejectionPercentage: '-', RejectionCRMHead: '-', RejectionRemark: '-' },
        rejectionPercent: "-",
        remark: "-",
        rm: "RM-15691 - RM",
        rmRate: 80,
        sTreatment: 0,
        saNumber: "-",
        scrapRate: 40,
        shareOfBusinessPercent: 0,
        sobPercentageExcel: 0,
        status: "Returned",
        surfaceTreatmentDetails: [],
        tCost: 0,
        technology: "Sheet Metal",
        technologyId: 1,
        toolAmortizationCost: 0,
        toolApplicability: { applicability: 'Applicability', value: 'Value' },
        toolApplicabilityValue: { toolTitle: '-', toolValue: 0 },
        toolMaintenanceCost: 0,
        toolMaintenanceCostApplicablity: 0,
        toolMaintenanceCostApplicablityValue: 0,
        toolPrice: 0,
        totalCost: 2600,
        totalTabSum: 2600,
        totalToolCost: 0,
        vendor: "BhuVendorTwo (1568)",
        vendorCode: "1568",
        vendorExcel: "BhuVendorTwo (1568)",
        vendorId: "dad1a53b-1792-48c1-ad91-74dbc9dcc60b",
        vendorName: "BhuVendorTwo",
        vendorPlantCode: "-",
        vendorPlantId: "-",
        vendorPlantName: "-",
        zbc: 2,
        tco: true,
        tcoValues: {
            WarrantyYears: "3",
            QualityPPM: "5000",
            MOQ: "2",
            SPQ: "1",
            LeadTime: "-",
            UOM: "kg",
            AvailableCapacity: "-",
            IncoTerms: "-",
            PayTerms: "-",
            LdClause: "-",
            TotalCostDetails: [{
                ApplicabilityCost: null,
                ApplicabilityIdRef: null,
                ApplicabilityType: null,
                NetCost: 0,
                Years: 3,
                Days: 90


            }]
        }
    },
];
