export const CONSTANT = {
    ADD: 'Add',
    UPDATE:'Update',
    SAVE: 'Save',
    PART: 'Part',
    NAME: 'Name',
    DESCRIPTION : 'Description',
    UOM:'Unit Of Measurement',
    NUMBER : 'Number',
    TYPE: 'type',
    GROUPCODE: 'Group Code',
    MASTER : 'Master',
    DETAILS : 'Details',
    BOM : 'BOM',
    CATEGORY: 'Category',
    TITLE: 'Title',
    MATERIAL: 'Material',
    PLANT: 'Plant',
    SUPPLIER: 'Supplier',
    ADDRESS: 'Address',
    COUNTRY: 'Country',
    STATE: 'State',
    CITY: 'City',
    EMAIL: 'email',
    CODE: 'code'
  };