export const categoriesMaster = [
    'Accommodations - Long Term',
    'Accommodations - Short Term',
    'Accompianist',
    'Accountant',
    'Acting Coach',
    'Agent-Screen',
    'Agent-Theatre',
    'Art School',
    'Audio/Visual Services',
    'Audition Services',
    'Backdrops',
    'Broadway Workshop',
    'Camp',
    'Cobbler',
    'Costume Rental',
    'Costumer',
    'Craft Services/Catering',
    'Dance School',
    'Demo Reels',
    'Dentist',
    'Dialect Coach',
    'Dramaturg',
    'Editing Services',
    'Entertainment Attorney',
    'Equipment Rental',
    'Film Festival',
    'Film School',
    'Fundraising',
    'Grant Writer',
    'Graphic Designer',
    'Guitar Instruction',
    'Hair Stylist',
    'Make Up Artist',
    'Music School',
    'Photographer',
    'Piano Instruction',
    'Private Dance Instruction',
    'Production Company',
    'Recording Studio',
    'Rehearsal Space',
    'Saxophone Instruction',
    'Set Medic/RN',
    'Set Teacher/Tutor',
    'Special FX Artist',
    'Spray Tan',
    'Stunt Training',
    'Summer Camp/Program',
    'Tailor/Seamstress',
    'Talent Managers',
    'Theatre',
    'Training Center',
    'Vocal Coach',
    'Wig Maker',
];


export const countries = [
    'Australia',
    'China',
    'India',
    'Mexico',
    'United Kingdom',
    'United States',
];

export const compensation = [
    'Scale',
    'Copy',
    'IMDB',
    'Travel & lodging',
];


export const sportsMaster = [
    'Aerobics',
    'Archery',
    'Badminton',
    'Baseball',
    'Basketball',
    'Baton Twirling',
    'Billiards/Pool Player',
    'Boating - engine',
    'Boating - Sail',
    'Body Building',
    'Body Surfing',
    'Bowling',
    'Boxing',
    'Canoeing',
    'Cheerleading',
    'Combat - Actual Service',
    'Combat - Stage',
    'Cricket',
    'Cycling',
    'Cycling - Mountain Biking',
    'Cycling - Unicycle',
    'Diving',
    'Equestrian - Dressage',
    'Equestrian - English',
    'Equestrian - General',
    'Equestrian - Racing',
    'Equestrian - Reining',
    'Equestrian - Rodeo',
    'Equestrian - Show Jumping',
    'Equestrian - Western',
    'Fencing',
    'Figure Skating',
    'Fishing',
    'Fly Fishing',
    'Football',
    'Frisbee',
    'Golf',
    'Gymnastics',
    'Hackey Sack',
    'Handball',
    'Hang Gliding',
    'Ice Hockey',
    'Hula Hoop',
    'Ice Skating',
    'Jet Skier',
    'Jockey',
    'Jump Rope',
    'Jump Rope - Double Dutch',
    'Karate - Goju-Ryu',
    'Karate - Kenpo',
    'Karate - Shito-Ryu',
    'Karate - Kung Fu',
    'Karate - Shotokan',
    'Karate: Wado-Ryu',
    'Kayaker',
    'Kick Boxing',
    'Kickboxing',
    'Lifeguard',
    'Lacrosse',
    'Martial Arts',
    'Martial Arts - Aikido',
    'Martial Arts - Hapkido',
    'Martial Arts - Jiu-Jitsu',
    'Martial Arts - Jujutsu',
    'Martial Arts - Judo',
    'Martial Arts - Katana',
    'Martial Arts - Kendo',
    'Martial Arts - Kobudo',
    'Martial Arts - Mixed',
    'Martial Arts - Sumo',
    'Martial Arts - Taekwondo',
    'Martial Arts - Tai Chi',
    'Motorcycle Riding - General',
    'Mountain Climbing',
    'Parkour',
    'Pilot - Balloonist',
    'Pilot - Glider',
    'Pilot - Helicopter',
    'Pilot - Single Engine',
    'Pilot - Twin and/or Jet',
    'Ping Pong',
    'Pogo Stick',
    'Racquetball',
    'Rappelling',
    'Rock Climber',
    'Rodeo - Bull Riding',
    'Roller Hockey',
    'Roller Skating',
    'Rollerblading',
    'Rugby',
    'Running - General',
    'Running - Long Distance',
    'Running - Sprint',
    'Sailing',
    'Sailor',
    'Scuba Diver',
    'Scuba Diving',
    'Sculling',
    'Segway',
    'Shooting - Revolver/Automatic',
    'Shooting - Rifle',
    'Shooting - Skeet/Trap',
    'Skateboard - slalom',
    'Skateboard - street',
    'Skateboard - stunts',
    'Skateboarding',
    'Sky Diving',
    'Snorkeling',
    'Snow Skiing - Competition',
    'Snow Skiing - Cross Country',
    'Snow Skiing - Downhill',
    'Snow Skiing - General',
    'Snowboarding',
    'Snowmobile',
    'Soccer',
    'Softball',
    'Speed Skating - ice',
    'Squash',
    'Surfing',
    'Swimming - ability - general',
    'Swimming - backstroke',
    'Swimming - breast stroke',
    'Swimming - butterfly',
    'Swimming - diving',
    'Swimming - freestyle',
    'Swimming - Synchronized',
    'Tennis',
    'Track & Field',
    'Trampoline',
    'Volleyball',
    'Water Skiing',
    'Weight Lift',
    'Wind Surfing',
    'Wrestling',
    'Yoga'
];

export const performanceMaster = [
    'Accordion',
    'Acoustic Bass',
    'Auctioneer',
    'Audio Prompter',
    'Autoharp',
    'Bagpipes',
    'Banjo',
    'Bartender - Vegas Style Flair',
    'Bassoon',
    'Bones',
    'Bongos',
    'Brass Instruments',
    'Cello',
    'Chef',
    'Chef - Garde Manger',
    'Chef - Pastry',
    'Chef - Saucier',
    'Chef - Sous',
    'Clarinet',
    'Clowning',
    'Comedian',
    'Conga',
    'Dance - Bhangara',
    'Dance - Breakdance',
    'Dance - Pole Dancing',
    'Dance Acro',
    'Dance Argentine Tango',
    'Dance Ballet',
    'Dance Ballroom',
    'Dance Belly',
    'Dance Bolero',
    'Dance Cha Cha',
    'Dance Flamenco',
    'Dance Hip Hop',
    'Dance Jazz',
    'Dance Line/Country',
    'Dance Mambo',
    'Dance Modern',
    'Dance Salsa',
    'Dance Rumba',
    'Dance Samba',
    'Dance Swing',
    'Dance Tap',
    'Dance Tango',
    'Dancer',
    'Disc Jockey',
    'Diving',
    'Drums',
    'Dulcimer',
    'Ear Prompter',
    'Fiddle',
    'Firearms',
    'Flute',
    'French Horn',
    'Guitar',
    'Guitar Bass',
    'Harmonica',
    'Host',
    'Impressionist',
    'Improvisation',
    'Juggler',
    'Licensed Driver',
    'Magician',
    'Medical Equipment',
    'Mime',
    'Modeling',
    'Motorcyclist',
    'Orchestral String Instruments',
    'Percussion',
    'Organ',
    'Pilot',
    'Piano',
    'Precision Driver',
    'Sax',
    'Singer',
    'Square Dance Caller',
    'Teleprompter',
    'Stunts',
    'Trombone',
    'Trumpet',
    'Tuba',
    'Ukulele',
    'Ventriloquist',
    'Violin',
    'Vocal Range: Alto',
    'Vocal Range: Bari-Tenor',
    'Vocal Range: Baritone',
    'Vocal Range: Bass',
    'Vocal Range: Mezzo Soprano',
    'Vocal Range: Soprano',
    'Vocal Range: Tenor',
    'Vocal Style: Legit',
    'Vocal Style: Belt',
    'Vocal Style: Rapper',
    'Voiceover',
    'Whistler'
];

export const ethnicAppearancesMaster = [
    'African',
    'American Indian',
    'African American',
    'Asian',
    'Caucasian',
    'East Indian',
    'Eastern European',
    'Filipino',
    'Hispanic',
    'Mediterranean',
    'Middle Eastern',
    'Multiracial',
    'Pacific Islander',
    'West Indies/Caribbean'
];

export const languagesMaster = [
    'Afrikaans',
    'Arabic',
    'Armenian',
    'Bengali',
    'Bulgarian',
    'Cantonese',
    'Chinese',
    'Danish',
    'Dutch',
    'English',
    'Farsi',
    'Filipino',
    'French',
    'French Canadian',
    'German',
    'Greek',
    'Hebrew',
    'Hindi',
    'Hungarian',
    'Indonesian',
    'Italian',
    'Japanese',
    'Korean',
    'Latin',
    'Lithuanian',
    'Mandarin',
    'Norwegian',
    'Pashtu',
    'Persian',
    'Polish',
    'Portuguese',
    'Punjabi',
    'Romanian',
    'Sign Language',
    'Russian',
    'Sotho',
    'Spanish',
    'Spanish - Mexico City',
    'Swahili',
    'Swedish',
    'Taiwanese',
    'Thai',
    'Turkish',
    'Urdu',
    'Vietnamese',
    'Yiddish',
    'Xhosa',
    'Zulu'
];

export const accentsMaster = [
    'African',
    'Asian',
    'Asian - Chinese',
    'Asian - Japanese',
    'Asian - Korean',
    'Australian',
    'Boston',
    'British - BBC English',
    'British - Birmingham',
    'British - Cockney',
    'British - Geordie',
    'British - Scouse/Liverpool',
    'British - Yorkshire',
    'Cajun',
    'Canadian',
    'Cockney',
    'Danish',
    'Dutch',
    'East Indian',
    'East-Bosnian',
    'Eastern European',
    'Filipino',
    'Finland',
    'French',
    'French - Canadian',
    'German',
    'Greek',
    'Hungarian',
    'Iraqi',
    'Irish',
    'Israeli',
    'Jamaican',
    'Italian',
    'Jewish/Yiddish',
    'Kosovo-Resava',
    'Mid-East',
    'Middle Eastern',
    'Midwest',
    'Minnesota',
    'New England',
    'New York',
    'Norwegian',
    'New Zealand',
    'Persian',
    'Philadelphia',
    'Polish',
    'Puerto Rican',
    'Russian',
    'Scandinavian',
    'Scottish',
    'Slavic - South Eastern Bloc',
    'Slovonian',
    'South African',
    'Southern',
    'Spanish',
    'Swedish',
    'Texan',
    'Welsh',
    'West Indian'
];

export const disabilitiesMaster = [
    'Amputee Arm',
    'Amputee Double',
    'Amputee Leg',
    'Amputee Single',
    'Asperger\'s',
    'Autism',
    'Blind or Low Vision',
    'Cerebral Palsy',
    'Deaf or Hard of Hearing',
    'Down syndrome',
    'Intellectual Disability',
    'Little Person',
    'Mobility Disability',
    'Wheelchair User',
    'Cane',
    'Crutches: Forearm',
    'Crutches: Underarm',
    'Leg Braces',
    'Mobility Scooter',
    'Prosthetic Limb: Arm',
    'Prosthetic Limb: Leg',
    'Service Animal',
    'Voice Box: Mechanical Larynx',
    'Walker',
    'Wheelchair: Manual',
    'Wheelchair: Power',
    'White Cane'
];

export const genders = [
    // { label: 'Select', value: '' },
    { label: 'Male', value: 'Male' },
    { label: 'Female', value: 'Female' },
    { label: 'Other', value: 'Other' },
];
export const eyeColorsMaster = [
    { label: 'Amber', value: 'Amber' },
    { label: 'Blue', value: 'Blue' },
    { label: 'Brown', value: 'Brown' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Green', value: 'Green' },
    { label: 'Hazel', value: 'Hazel' },
    { label: 'Red', value: 'Red' },
    { label: 'Violet', value: 'Violet' },
];


export const heightInFeetArray = [
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 }
];

export const heightInInchesArray = [
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 },
    { label: '10', value: 10 },
    { label: '11', value: 11 },

];

export const typeOfListingsMaster = [
    { label: 'Personal Business', value: 'Personal Business' },
    { label: 'Public Company', value: 'Public Company' },
    { label: 'Enterprise School', value: 'Enterprise School' },
    { label: 'Other', value: 'Other' },
];

export const experianceTypeMaster = [
//    { label: 'Select', value: '' },
    { label: 'Theater experience', value: 'theatreexperience' },
    { label: 'Film experience', value: 'filmexperience' },
    { label: 'TV experience', value: 'tvexperience' },
    { label: 'Education/training', value: 'educationaltraining' },
];

export const hairColorAndTypeArray = [
    // { label: 'Select', value: '' },
    { label: 'Auburn', value: 'Auburn' },
    { label: 'Bald', value: 'Bald' },
    { label: 'Black', value: 'Black' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Red', value: 'Red' },
    { label: 'White', value: 'White' },
    { label: 'Salt and Pepper', value: 'Salt and Pepper' },
    { label: 'Blonde (Dark)', value: 'Blonde (Dark)' },
    { label: 'Blonde (Light)', value: 'Blonde (Light)' },
    { label: 'Brown (Dark)', value: 'Brown (Dark)' },
    { label: 'Brown (Light)', value: 'Brown (Light)' },
    { label: 'Blonde (Medium)', value: 'Blonde (Medium)' },
    { label: 'Blonde (Platinum)', value: 'Blonde (Platinum)' },
    { label: 'Blonde (Strawberry)', value: 'Blonde (Strawberry)' },

];

export const hairLengthArray = [
    // { label: 'Select', value: '' },
    { label: 'Afro', value: 'Afro' },
    { label: 'Long', value: 'Long' },
    { label: 'Receding', value: 'Receding' },
    { label: 'Short', value: 'Short' },
    { label: 'Shoulder Length', value: 'Shoulder Length' },
    { label: 'Bald (On Top)', value: 'Bald (On Top)' },
    { label: 'Bald (Totally)', value: 'Bald (Totally)' },
];

// export const typeOfOpprtunities = [
//     { label: 'Select', value: '' },
//     { label: 'Series (web or TV)', value: 'Series (web or TV)' },
//     { label: 'Theatre', value: 'Theatre' },
//     { label: 'Film', value: 'Film' },
//     { label: 'Commercial', value: 'Commercial' },
//     { label: 'Workshop (only for paid members)', value: 'Workshop (only for paid members)' },
//     { label: 'Camp (only for paid members)', value: 'Camp (only for paid members)' },
//     { label: 'Audition', value: 'Audition' },
//     { label: 'Crew call', value: 'Crew call' },
//     { label: 'Master class (only for paid members)', value: 'Master class (only for paid members)' },
//     { label: 'Intensive', value: 'Intensive' },
//     { label: 'Read through', value: 'Read through' },
//     { label: 'Special (only for paid members)', value: 'Special (only for paid members)' },
// ];

export const typeOfOpprtunities = [
    { label: 'Select', value: '' },
    {
        label: 'Auditions/Casting Calls', value: 'Auditions/Casting Calls',
        subCategories: [
            { label: 'Select', value: '' },
            { label: 'Commercial', value: 'Commercial' },
            { label: 'Film', value: 'Film' },
            { label: 'Live Entertainment', value: 'Live Entertainment' },
            { label: 'Series', value: 'Series' },
            { label: 'Table Read', value: 'Table Read' },
            { label: 'Theatre', value: 'Theatre' },
            { label: 'Voiceover', value: 'Voiceover' }
        ]
    },
    {
        label: 'Crew Call',
        value: 'Crew Call',
        subCategories: []
    },
    {
        label: 'Training',
        value: 'Training',
        subCategories: [
            { label: 'Select', value: '' },
            { label: 'Camp', value: 'Camp' },
            { label: 'Intensive', value: 'Intensive' },
            { label: 'Masterclass', value: 'Masterclass' },
            { label: 'Monthly/Weekly Class', value: 'Monthly/Weekly Class' },
        ]
    },
];

export const unionsOption = [
    // { label: 'Select', value: '' },
    { label: 'Yes', value: true },
    { label: 'No', value: false },
];

export const Opprtunities = [
    // { label: 'Select', value: '' },
    { label: 'FINAL OPPORTUNITY 1', value: '5c8a1c87b2f5ab3ab939e02f' },
    { label: 'Nilesh Movie', value: '5c8a1c87b2f5ab3ab939e02f' },
];


/** ADD ROLE MASTERS */

export const ageMaster = [
    // { label: 'Select', value: '' },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 },
    { label: '10', value: 10 },
    { label: '11', value: 11 },
    { label: '12', value: 12 },
    { label: '13', value: 13 },
    { label: '14', value: 14 },
    { label: '15', value: 15 },
    { label: '16', value: 16 },
    { label: '17', value: 17 },
    { label: '18', value: 18 },
    { label: '19', value: 19 },
    { label: '20', value: 20 },
    { label: '21', value: 21 },
    { label: '22', value: 22 },
    { label: '23', value: 23 },
    { label: '24', value: 24 },
    { label: '25', value: 25 },
    { label: '26', value: 26 },
    { label: '27', value: 27 },
    { label: '28', value: 28 },
    { label: '29', value: 29 },
    { label: '30', value: 30 },
    { label: '31', value: 31 },
    { label: '32', value: 32 },
    { label: '33', value: 33 },
    { label: '34', value: 34 },
    { label: '35', value: 35 },
    { label: '36', value: 36 },
    { label: '37', value: 37 },
    { label: '38', value: 38 },
    { label: '39', value: 39 },
    { label: '40', value: 40 },
    { label: '41', value: 41 },
    { label: '42', value: 42 },
    { label: '43', value: 43 },
    { label: '44', value: 44 },
    { label: '45', value: 45 },
    { label: '46', value: 46 },
    { label: '47', value: 47 },
    { label: '48', value: 48 },
    { label: '49', value: 49 },
    { label: '50', value: 50 },
    { label: '51', value: 51 },
    { label: '52', value: 52 },
    { label: '53', value: 53 },
    { label: '54', value: 54 },
    { label: '55', value: 55 },
    { label: '56', value: 56 },
    { label: '57', value: 57 },
    { label: '58', value: 58 },
    { label: '59', value: 59 },
    { label: '60', value: 60 },
    { label: '61', value: 61 },
    { label: '62', value: 62 },
    { label: '63', value: 63 },
    { label: '64', value: 64 },
    { label: '65', value: 65 },
    { label: '66', value: 66 },
    { label: '67', value: 67 },
    { label: '68', value: 68 },
    { label: '69', value: 69 },
    { label: '70', value: 70 },
    { label: '71', value: 71 },
    { label: '72', value: 72 },
    { label: '73', value: 73 },
    { label: '74', value: 74 },
    { label: '75', value: 75 },
    { label: '76', value: 76 },
    { label: '77', value: 77 },
    { label: '78', value: 78 },
    { label: '79', value: 79 },
    { label: '80', value: 80 },
    { label: '81', value: 81 },
    { label: '82', value: 82 },
    { label: '83', value: 83 },
    { label: '84', value: 84 },
    { label: '85', value: 85 },
    { label: '86', value: 86 },
    { label: '87', value: 87 },
    { label: '88', value: 88 },
    { label: '89', value: 89 },
    { label: '90', value: 90 },
    { label: '91', value: 91 },
    { label: '92', value: 92 },
    { label: '93', value: 93 },
    { label: '94', value: 94 },
    { label: '95', value: 95 },
    { label: '96', value: 96 },
    { label: '97', value: 97 },
    { label: '98', value: 98 },
    { label: '99', value: 99 },
    { label: '100', value: 100 },
];

export const clothingSizeMaster = [
    { label: 'Small', value: 'Small' },
    { label: 'Medium', value: 'Medium' },
    { label: 'Large', value: 'Large' },
    { label: 'X-Large', value: 'X-Large' },
    { label: 'XX-Large', value: 'XX-Large' },
];

export const roleHairColorTypeMaster = [
    // { label: 'Select', value: '' },
    { label: 'Auburn', value: 'Auburn' },
    { label: 'Bald', value: 'Bald' },
    { label: 'Black', value: 'Black' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Red', value: 'Red' },
    { label: 'White', value: 'White' },
    { label: 'Salt and Pepper', value: 'Salt and Pepper' },
    { label: 'Blonde (Dark)', value: 'Blonde (Dark)' },
    { label: 'Blonde (Light)', value: 'Blonde (Light)' },
    { label: 'Brown (Dark)', value: 'Brown (Dark)' },
    { label: 'Brown (Light)', value: 'Brown (Light)' },
    { label: 'Blonde (Medium)', value: 'Blonde (Medium)' },
    { label: 'Blonde (Platinum)', value: 'Blonde (Platinum)' },
    { label: 'Blonde (Strawberry)', value: 'Blonde (Strawberry)' },
];

export const roleEyeColorsMaster = [
    // { label: 'Select', value: '' },
    { label: 'Amber', value: 'Amber' },
    { label: 'Blue', value: 'Blue' },
    { label: 'Brown', value: 'Brown' },
    { label: 'Gray', value: 'Gray' },
    { label: 'Green', value: 'Green' },
    { label: 'Hazel', value: 'Hazel' },
    { label: 'Red', value: 'Red' },
    { label: 'Violet', value: 'Violet' },
];

export const minVocalMaster = [
    // { label: 'Select', value: '' },
    { label: 'B3', value: 'B3' },
    { label: 'G3', value: 'G3' },
    { label: 'E3', value: 'E3' },
    { label: 'C3', value: 'C3' },
    { label: 'G2', value: 'G2' },
    { label: 'D2', value: 'D2' },
];


export const maxVocalMaster = [
    // { label: 'Select', value: '' },
    { label: 'G6', value: 'G6' },
    { label: 'A5', value: 'A5' },
    { label: 'F5', value: 'F5' },
    { label: 'C6', value: 'C6' },
    { label: 'B4', value: 'B4' },
    { label: 'G4', value: 'G4' },
    { label: 'E4', value: 'E4' },
];

export const sorting = [
    { label: 'Distance', value: 'distance' },
    { label: 'Newest', value: 'newest' },
    { label: 'Sort A-Z', value: 'AtoZ' },
    { label: 'Sort Z-A', value: 'ZtoA' },
];

export const distanceDataSorting = [
    { label: '30 miles', value: 30 },
    { label: '60 miles', value: 60 },
    { label: '100 miles', value: 100 },
];

export const chartDataSorting = [
    { label: 'Day', value: 'day' },
    { label: 'Week', value: 'week' },
    { label: 'Month', value: 'month' },
];

export const userCategoriesMaster = [
    '2nd AD',
    'Actor',
    'Animator',
    'Art Director',
    'Assistant Director',
    'Audio Engineer',
    'Best Boy',
    'Best Boy Grip',
    'Camera',
    'Carpenter',
    'Casting Director',
    'Director - Music ',
    'Comic',
    'Composer',
    'Conductor',
    'Costume Designer',
    'CostumeAssistant',
    'Costumer',
    'Dancer',
    'Director of Photography',
    'Director - Live Production',
    'Director - Documentary',
    'Director - Film',
    'Director - Music',
    'Director - Theatre',
    'Director - TV',
    'Dramaturg',
    'Electrician',
    'Exec Producer',
    'FX Make Up Artist',
    'Gaffer',
    'Grahic Artist',
    'Grip',
    'Hair',
    'Hand Model',
    'Headshot Photographer',
    'House Manager',
    'Key Grip',
    'Lighting Designer',
    'Line Producer',
    'Location',
    'Make Up Artist',
    'Model',
    'Musician',
    'Playwright',
    'Producer',
    'Production Assistant (do we need two for set and talent)',
    'Production Coordinator',
    'Production Manager',
    'Production Supervisor',
    'Proofreader',
    'Propsmaster',
    'Publicist',
    'Puppeteer',
    'Scenic Designer',
    'Screenwriter',
    'Script Supervisor',
    'Set Designer',
    'Set EMT / Medic',
    'Set Nurse',
    'Set Tutor',
    'Show Runner',
    'Sound Designer',
    'Sound Mixer',
    'Spotlight Operator',
    'Stage Manager',
    'Stagehand',
    'Stand In',
    'Still Photographer',
    'Stunt Coordinator',
    'Stuntman / women',
    'Technical Director',
    'Tour Manager',
    'Vocalist',
    'Wardrobe',
    'Wardrobe Superviser'
];
