export const MESSAGES = {
  INVALID_EMAIL_PASSWORD: 'Either email or password is invalid or your account is inactive.',
  SOME_ERROR: 'Opps! Something went wrong. Please try again later.',
  LOGIN_SUCCESS: 'You are successfully logged in.',
  UPDATE_PASSWORD_SUCCESS: 'Your password has been successfully updated.',
  NOT_VERIFIED_USER: 'Your account is pending for verification. Please verify your account for login.',
  PART_ADD_SUCCESS: 'Part added successfully.',
  PART_DELETE_SUCCESS: 'Part has been deleted.',
  UPDATE_PART_SUCESS: 'Part updated successfully.',
  UOM_ADD_SUCCESS: 'Unit Of measurement added successfully.',
  UPDATE_UOM_SUCESS: 'Unit Of measurement updated successfully.',
  DELETE_UOM_SUCCESS: 'Unit Of measurement deleted successfully.',
  CONFIRM_DELETE: 'Are you sure you want to delete This.',
  CATEGORY_TYPE_ADDED_SUCCESS: 'Category type added successfully.',
  CATEGORY_ADD_SUCCESS: 'Category created successfully.',
  MATERIAL_ADDED_SUCCESS: 'Material added successfully.',
  PLANT_ADDED_SUCCESS: 'Plant created successfully.',
  SUPPLIER_ADDED_SUCCESS: 'Supplier added successfully.',
  GRADE_ADD_SUCCESS: 'Row material grade added successfully.',
  SPECIFICATION_ADD_SUCCESS: 'Row material specification added successfully.',
  BOM_ADD_SUCCESS: 'Bill of material added successfully.',
  BOP_ADD_SUCCESS: 'Bought out part added successfully.',
  PROCESS_ADD_SUCCESS: 'Process added successfully.',
  FUEL_ADD_SUCCESS: 'Fuel added successfully.',
  FUEL_DETAIL_ADD_SUCCESS: 'Fuel Details added successfully.',
  OTHER_OPERATION_ADD_SUCCESS: 'Other Operation added successfully.',
  CED_OTHER_OPERATION_ADD_SUCCESS: 'CED Other Operation added successfully.',
  MATERIAL_ADD_SUCCESS: 'Row material details added successfully.'
};

