export const MESSAGES = {
  INVALID_EMAIL_PASSWORD: 'Either email or password is invalid or your account is inactive.',
  SOME_ERROR: 'Opps! Something went wrong. Please try again later.',
  LOGIN_SUCCESS: 'You are successfully logged in.',
  LOGOUT_SUCCESS: 'You are successfully logged out.',
  UPDATE_PASSWORD_SUCCESS: 'Your password has been successfully updated.',
  NOT_VERIFIED_USER: 'Your account is pending for verification. Please verify your account for login.',

  //MASTERS
  PART_ADD_SUCCESS: 'Part added successfully.',
  PART_DELETE_SUCCESS: 'Part has been deleted.',
  UPDATE_PART_SUCESS: 'Part updated successfully',
  MESSAGE_SENT_EXCEPT_USER: 'Message has been sent except the user',
  UOM_ADD_SUCCESS: 'Unit Of measurement added successfully',
  UPDATE_UOM_SUCESS: 'Unit Of measurement updated successfully',
  DELETE_UOM_SUCCESS: 'Unit Of measurement deleted successfully',
  CONFIRM_DELETE: 'Are you sure you want to delete This',
  CATEGORY_TYPE_ADDED_SUCCESS: 'Category type added successfully',
  CATEGORY_ADD_SUCCESS: 'Category created successfully',
  MATERIAL_ADDED_SUCCESS: 'Material added successfully',
  PLANT_ADDED_SUCCESS: 'Plant created successfully',
  SUPPLIER_ADDED_SUCCESS: 'Supplier added successfully',
  GRADE_ADD_SUCCESS: 'Row material grade added successfully',
  SPECIFICATION_ADD_SUCCESS: 'Row material specification added successfully',
  BOM_ADD_SUCCESS: 'Bill of material added successfully',
  OTHER_OPERATION_ADD_SUCCESS: 'Other Operation added successfully',
  CED_OTHER_OPERATION_ADD_SUCCESS: 'CED Other Operation added successfully',
  MHR_MASTER_ADD_SUCCESS: 'MHR Master added successfully',
  OPERATION_ADD_SUCCESS: 'Operation added successfully',
  MATERIAL_ADD_SUCCESS: 'Row material details added successfully.',
  FREIGHT_ADDED_SUCCESS: 'Freight added successfully',
  LABOUR_ADDED_SUCCESS: 'Labour added successfully',
  OVERHEAD_PROFIT_ADDED_SUCCESS: 'Overhead profit added successfully',
  DEPRECIATION_ADD_SUCCESS: 'Depreciation added successfully',
  DELETE_FUEL_DETAIL_SUCCESS: 'Fuel detail deleted successfully',
  DELETE_FUEL_TYPE_SUCCESS: 'Fuel type deleted successfully',
  DELETE_PLANT_SUCCESS: 'Plant deleted successfully',
  UPDATE_PLANT_SUCESS: 'Plant updated successfully',
  DELETE_PROCESS_SUCCESS: 'Process deleted successfully',
  UPDATE_PROCESS_SUCCESS: 'Process updated successfully',
  PROCESS_ADD_SUCCESS: 'Process added successfully',
  DELETE_BOP_SUCCESS: 'Bought out part deleted successfully',
  DELETE_FREIGHT_SUCCESS: 'Freight deleted successfully',
  UPDATE_FREIGHT_SUCESS: 'Freight updated successfully',
  DELETE_LABOUR_SUCCESS: 'Labour deleted successfully',
  UPDATE_LABOUR_SUCCESS: 'Labour updated successfully',
  DELETE_SUPPLIER_SUCCESS: 'Supplier deleted successfully',
  UPDATE_SUPPLIER_SUCESS: 'Supplier updated successfully',
  UPDATE_BOP_SUCESS: 'BOP updated successfully',
  FUEL_DETAIL_ADD_SUCCESS: 'Fuel detail added successfully',
  FUEL_ADD_SUCCESS: 'Fuel added successfully',
  ADD_BOP_SUCCESS: 'BOP added successfully',
  BOP_ADD_SUCCESS: 'BOP added successfully',
  INTEREST_RATE_ADDED_SUCCESS: 'Suppiler interest rate added successfully',
  DELETE_INTEREST_RATE_SUCCESS: 'Supplier interest rate deleted successfully',
  UPDATE_INTEREST_RATE_SUCESS: 'Supplier interest rate updated successfully',
  ADD_PART_WITH_SUPPLIER_SUCCESS: 'Supplier has been added successfully.',
  NEW_COSTING_CREATE_SUCCESS: 'New sheetmetal costing created successfully',
  BOM_DELETE_SUCCESS: 'BOM has been deleted.',
  WEIGHT_ADD_SUCCESS: 'Weight specification added successfully',
  SAVE_OTHER_OPERATION_SUCCESS: 'Other Operation saved successfully.',
  SAVE_PROCESS_COSTING_SUCCESS: 'Process costing saved successfully.',
  UPDATE_COSTING_OTHER_OPERATION_SUCCESS: 'Other Operation has been updated.',
  COSTING_HAS_BEEN_DRAFTED_SUCCESSFULLY: 'Costing has been drafted successfully.',
  SELECT_PART_FOR_ZBC_COSTING: 'Please select part for zbc costing.',

  //MACHINE MASTER
  DELETE_MACHINE_SUCCESS: 'Machine has been deleted successfully.',
  MACHINE_DELETE_ALERT: 'Are you sure you want to delete Machine?',

  //POWER MASTER
  POWER_DELETE_ALERT: 'Are you sure you want to delete Power?',

  //USER
  ADD_USER_SUCCESSFULLY: 'User has been added successfully.',

  //ROLE
  ADD_ROLE_SUCCESSFULLY: 'Role has been added successfully.',
  UPDATE_ROLE_SUCCESSFULLY: 'Role has been updated successfully.',
  DELETE_ROLE_SUCCESSFULLY: 'Role has been deleted successfully.',
  ROLE_DELETE_ALERT: 'Are you sure you want to delete Role?',

  //DEPARTMENT
  ADD_DEPARTMENT_SUCCESSFULLY: 'Department has been added successfully.',
  UPDATE_DEPARTMENT_SUCCESSFULLY: 'Department has been updated successfully.',
  DELETE_DEPARTMENT_SUCCESSFULLY: 'Department has been deleted successfully.',
  DEPARTMENT_DELETE_ALERT: 'Are you sure you want to delete Department?',

  //LEVEL
  ADD_LEVEL_SUCCESSFULLY: 'User level has been added successfully.',
  UPDATE_LEVEL_SUCCESSFULLY: 'Level has been updated successfully.',
  DELETE_LEVEL_SUCCESSFULLY: 'Level has been deleted successfully.',
  LEVEL_DELETE_ALERT: 'Are you sure you want to delete Level?',
  ADD_LEVEL_USER_SUCCESSFULLY: 'Level of users has been added successfully.',

  //ADDITIONAL FREIGHT
  ADDITIONAL_FREIGHT_ADD_SUCCESS: 'Packaging has been added successfully.',
  DELETE_ADDITIONAL_FREIGHT_SUCCESS: 'Additional Freight has been deleted successfully.',
  WEIGHT_SPEC_UPDATE_SUCCESS: 'Weight specification updated successfully.',
  WEIGHT_SPEC_ADDED_SUCCESS: 'Weight specification added successfully',
  SELECT_SUPPLIER_BEFORE_ADD_VALUE: 'Please add supplier before adding value.',
  SOB_LESS_THAN_100: 'SOB Sould be less than 100%.',
  SOB_GREATER_THAN_ZERO: 'SOB Sould be greater than 0.',
  COSTING_SAVED_SUCCESSFULLY: 'Costing has been saved successfully.',
  COSTING_SENT_FOR_APPROVAL_SUCCESSFULLY: 'Costing has been sent for approval.',
  SELECT_PLANT_FOR_COSTING: 'Plant should not be empty.',

  //PRIVILEGE
  ADD_PRIVILEGE_PAGE_SUCCESSFULLY: 'Privilege page added successfully.',
  ADD_PRIVILEGE_PAGE_ROLEWISE_SUCCESSFULLY: 'Privilege page role wise added successfully.',
  ADD_PRIVILEGE_PAGE_USERWISE_SUCCESSFULLY: 'Privilege page user wise added successfully.',
  ADDITIONAL_PERMISSION_ADDED_SUCCESSFULLY: 'Additional permission has been added successfully.',

};

