export const MESSAGES = {
  INVALID_EMAIL_PASSWORD: 'Either email or password is invalid or your account is inactive.',
  LOGIN_SUCCESS: 'You are successfully logged in.',
  UPDATE_PASSWORD_SUCCESS: 'Your password has been successfully updated.',
  NOT_VERIFIED_USER: 'Your account is pending for verification. Please verify your account for login.',
  BASIC_PROFILE_INFO_INCOMPLETE: 'Your basic profile information is incomplete. Please complete these details to access the application.',
  SOME_ERROR: 'Opps! Something went wrong. Please try again later.',
  PROFILE_UPDATE_SUCESS: 'Your profile has been updated successfully.',
  ADD_EXPERIANCE_SUCESS: 'The experience has been added successfully.',
  DELETE_EXPERIANCE_SUCESS: 'The experience has been deleted successfully.',
  UPDATE_EXPERIANCE_SUCESS: 'Experience has been updated successfully.',
  UPDATE_PRODUCTION_PROFILE_SUCESS: 'Production company details has been updated successfully.',
  MAX_UPLOAD_IMAGE_SIZE: ' Please upload only image files with size equal to or less than 5MB.',
  DELETE_MEDIA_SUCCESS: 'The media has been deleted successfully.',
  INVALID_EMAIL: 'It seems, the given email address is invalid.',
  DELETE_AWARD_CONFIRMATION: 'Are you sure you want to delete this award ?',
  DELETE_SERVICE_CONFIRMATION: 'Are you sure you want to delete this service ?',
  DELETE_MEDIA_CONFIRMATION: 'Are you sure you want to delete this media ?',
  SET_IMAGE_AS_PROFILE_PICTURE: 'Are you sure ? You want to set this image as profile picture?',
  TEMPORARY_PASSWORD_SEND: 'We have sent an email with a temporary password. Kindly check your email.',
  VERIFICATION_SUCCESS: 'Your account has been verified successfully! Please subscribe for a plan.',
  PRODUCTION_UPDATE_SUCESS: 'Production Company details has been updated successfully.',
  MEDIA_FILE_UPLOAD_SUCESS: 'File has been uploaded successfully.',
  MAX_UPLOAD_VIDEO_SIZE: 'Please upload only video files with size equal to or less than 30MB.',
  FILL_SOCIAL_LINK: 'Please complete at least one social input.',
  LINKS_UPDATE_SUCESS: 'Social link(s) updated successfully.',
  REGISTRATION_SUCCESS: 'Your account has been registered successfully. Please follow verification process for successful login.',
  VERIFICATION_FAIL: 'Your email token verification is failed. Please try again.',
  REGISTRATION_FAIL: 'Signup using email is failed. Please try again.',
  RESEND_VARIFICATION_CODE_FAIL: 'Something went wrong in resending verification token on your registered email address.',
  LOGOUT_SUCCESS: 'You are successfully logged out.',
  USER_PROFILE_IMAGE_UPLOAD_SUCCESS: 'User profile image has been uploaded successfully.',
  USER_HEADSHOT_IMAGE_UPLOAD_SUCCESS: 'User headshot image has been uploaded successfully.',
  PRODUCTION_PROFILE_IMAGE_UPLOAD_SUCCESS: 'Production company logo has been uploaded successfully.',
  PRODUCTION_HEADSHOT_IMAGE_UPLOAD_SUCCESS: 'Production company headshot has been uploaded successfully.',
  FIELD_ERROR_MESSAGE: 'Please check and correct the error in the form.',
  EMAIL_ALREADY_EXIST: 'An account for the specified email address already exists. Please try another email address.',
  ADD_NEW_ROLE_SUCESS: 'The role has been added successfully.',
  ROLE_DELETE_SUCESS: 'The opportunity role has been deleted successfully',
  UPDATE_OPPORTUNITY_ROLE_SUCESS: 'The role has been updated successfully.',
  OPPORTUNITY_SUCCESS: 'The opportunity has been saved successfully.',
  OPPORTUNITY_PUBLISH: 'The opportunity has been published successfully.',
  OPPORTUNITY_DELETE_SUCCESS: 'The opportunity has been deleted successfully.',
  AUDITION_ADDED: 'The audition has been successfully added.',
  PRODUCTION_DATE_ADDED: 'The production date has been successfully added.',
  PRODUCTION_DATE_REMOVED: 'The production date has been successfully removed.',
  APPLY_ROLE_SUCESS: 'You have successfully applied for the role.',
  ASK_CALENDER_PERMISSON: "It seems you didn't allow the calender access permission. Please go in application permission settings, allow the permission and try it again.",
  ASK_TO_SELECT_AUDITION_SLOT: 'Please select at least one audition location & date.',
  APPLY_ROLE_SUCCESS: 'Your opportunity has been successfully applied.',
  INVALID_URL: 'It seems, you are trying to access invalid URL',
  NOTIFICATION_SETTING_SUCCESS: 'Your notification settings have been updated successfully.',
  BLOCKED_SUCCESS: 'User blocked successfully.',
  UNBLOCK_SUCCESS: 'User unblocked successfully.',
  ALREADY_APPLIED_OPPORTUNITY: 'You are already applied for this opportunity.',
  UNAUTHORIZED_USER_TO_ACCESS_URL: 'It seems, you are the unauthorized user to access this URL.',
  DISABLED_LOCATION_PERMISSION: 'Permission to access your Location is disabled. Please allow from application permission.',
  ENABLE_LOCATION_ALERT: 'Please go in app settings and allow your location permission for getting the result based on current location.',
  PLAN_SUBSCRIPTION_SUCCESS: 'Payment has been done now we are setting up your account',
  PLAN_SUBSCRIPTION_ERROR: 'Oops! There is some error in subscription please try again later.',
  NO_PLAN_SUBSCRIPTION: 'Oops! It Seems you not done any subscription. Please choose any plan.',
  SUBSCRIPTION_EXPIRED: 'Oops! It Seems your Subscription is expired. Please take new plan.',
  PURCHASE_PAID_PLAN: 'Currently you have subscribed to free plan. Please choose a paid plan to unlock this feature.',
  MESSAGE_MOVE_CONFIRM: 'Are you sure you want to move this message ?',
  BLOCK_USER_CONFIRM: 'Are you sure you want to block this user?',
  DELETE_MESSAGE_CONFIRM: 'Are you sure you want to delete this message ?',
  MESSAGE_SENT_EXCEPT_USER: 'Message has been sent except the user',
  MESSAGE_DELETE_SUCCESS: 'Message has been deleted.'
};
 
